/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.mediactl.clustarr.api.common.v1alpha1.Attempts
  map:
    fields:
    - name: count
      type:
        scalar: numeric
    - name: initial
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: latest
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.mediactl.clustarr.api.common.v1alpha1.FileFingerprint
  map:
    fields:
    - name: modTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: sizeBytes
      type:
        scalar: numeric
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.EmbeddedSpec
  map:
    fields:
    - name: extract
      type:
        scalar: boolean
      default: true
    - name: ignoreASS
      type:
        scalar: boolean
      default: false
    - name: ignorePGS
      type:
        scalar: boolean
      default: false
    - name: ignoreVobSub
      type:
        scalar: boolean
      default: false
    - name: skipCommentary
      type:
        scalar: boolean
      default: true
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ExistingSub
  map:
    fields:
    - name: langKey
      type:
        scalar: string
    - name: path
      type:
        scalar: string
    - name: source
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleSource
    - name: streamIndex
      type:
        scalar: numeric
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.HIExtension
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.HIPolicy
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.LanguageItem
  map:
    fields:
    - name: audioExclude
      type:
        scalar: boolean
      default: false
    - name: audioOnlyInclude
      type:
        scalar: boolean
      default: false
    - name: forced
      type:
        scalar: boolean
      default: false
    - name: hi
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.HIPolicy
      default: prefer
    - name: key
      type:
        scalar: string
    - name: language
      type:
        scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ProviderQuota
  map:
    fields:
    - name: remaining
      type:
        scalar: numeric
    - name: resetAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ScorePct
  map:
    fields:
    - name: episode
      type:
        scalar: numeric
      default: 90
    - name: movie
      type:
        scalar: numeric
      default: 70
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SearchSpec
  map:
    fields:
    - name: adaptiveDelay
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
      default: 504h
    - name: adaptiveDelta
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
      default: 168h
    - name: interval
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
      default: 6h
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleItem
  map:
    fields:
    - name: attempts
      type:
        namedType: com.github.mediactl.clustarr.api.common.v1alpha1.Attempts
    - name: downloadedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: langKey
      type:
        scalar: string
    - name: lastError
      type:
        scalar: string
    - name: nextSearchAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: path
      type:
        scalar: string
    - name: provider
      type:
        scalar: string
    - name: score
      type:
        scalar: numeric
    - name: scoreOutOf
      type:
        scalar: numeric
    - name: state
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleItemState
    - name: subtitleID
      type:
        scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleItemState
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleMod
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfile
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfileSpec
    - name: status
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfileStatus
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfileList
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: items
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfile
          elementRelationship: atomic
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfileSpec
  map:
    fields:
    - name: cutoff
      type:
        scalar: string
    - name: default
      type:
        scalar: boolean
      default: false
    - name: embedded
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.EmbeddedSpec
      default: {}
    - name: hiExtension
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.HIExtension
      default: sdh
    - name: languageEquals
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: languages
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.LanguageItem
          elementRelationship: associative
          keys:
          - key
    - name: minScorePercent
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ScorePct
      default: {}
    - name: mods
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleMod
          elementRelationship: atomic
    - name: mustContain
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: mustNotContain
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: originalFormat
      type:
        scalar: boolean
      default: false
    - name: providers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: search
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SearchSpec
      default: {}
    - name: selector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: sync
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SyncSpec
    - name: upgrade
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.UpgradeSpec
      default: {}
    - name: whisper
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.WhisperSpec
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfileStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: matchingFiles
      type:
        scalar: numeric
    - name: observedGeneration
      type:
        scalar: numeric
    - name: wantedKeys
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProvider
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderSpec
    - name: status
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderStatus
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderList
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: items
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProvider
          elementRelationship: atomic
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderSpec
  map:
    fields:
    - name: enabled
      type:
        scalar: boolean
      default: true
    - name: endpoint
      type:
        scalar: string
    - name: languages
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: options
      type:
        map:
          elementType:
            scalar: string
    - name: priority
      type:
        scalar: numeric
      default: 50
    - name: requestsPerSecondMilli
      type:
        scalar: numeric
      default: 5000
    - name: secretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: type
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderType
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: errorsLast120s
      type:
        scalar: numeric
    - name: hiVerifiable
      type:
        scalar: boolean
    - name: lastSuccessAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: observedGeneration
      type:
        scalar: numeric
    - name: quota
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ProviderQuota
    - name: throttleReason
      type:
        scalar: string
    - name: throttledUntil
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: tokenExpiresAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProviderType
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequest
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestSpec
    - name: status
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestStatus
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestList
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: items
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequest
          elementRelationship: atomic
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestPhase
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestSpec
  map:
    fields:
    - name: forceSearch
      type:
        scalar: boolean
      default: false
    - name: languages
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: mediaFileRef
      type:
        scalar: string
    - name: minScoreOverride
      type:
        scalar: numeric
    - name: profileRef
      type:
        scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: existing
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ExistingSub
          elementRelationship: atomic
    - name: fileFingerprint
      type:
        namedType: com.github.mediactl.clustarr.api.common.v1alpha1.FileFingerprint
    - name: items
      type:
        list:
          elementType:
            namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleItem
          elementRelationship: associative
          keys:
          - langKey
    - name: observedGeneration
      type:
        scalar: numeric
    - name: phase
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleRequestPhase
    - name: probeHash
      type:
        scalar: string
    - name: profileGeneration
      type:
        scalar: numeric
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleSource
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SyncSpec
  map:
    fields:
    - name: enabled
      type:
        scalar: boolean
      default: false
    - name: gss
      type:
        scalar: boolean
      default: true
    - name: maxOffsetSeconds
      type:
        scalar: numeric
      default: 60
    - name: noFixFramerate
      type:
        scalar: boolean
      default: true
    - name: thresholdPercent
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.ScorePct
      default: {}
    - name: tool
      type:
        namedType: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SyncTool
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.SyncTool
  scalar: string
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.UpgradeSpec
  map:
    fields:
    - name: enabled
      type:
        scalar: boolean
      default: true
    - name: interval
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
      default: 12h
    - name: lookbackDays
      type:
        scalar: numeric
      default: 7
    - name: minDeltaPoints
      type:
        scalar: numeric
      default: 3
- name: com.github.mediactl.clustarr.api.subtitle.v1alpha1.WhisperSpec
  map:
    fields:
    - name: enabled
      type:
        scalar: boolean
      default: false
    - name: providerRef
      type:
        scalar: string
- name: io.k8s.api.core.v1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: operator
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorOperator
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta
  map:
    fields:
    - name: continue
      type:
        scalar: string
    - name: remainingItemCount
      type:
        scalar: numeric
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: shardInfo
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ShardInfo
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ShardInfo
  map:
    fields:
    - name: selector
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
