# Clustarr build tooling. Targets follow kubebuilder conventions.

GOBIN ?= $(shell go env GOPATH)/bin
CONTROLLER_GEN ?= $(GOBIN)/controller-gen
SETUP_ENVTEST ?= $(GOBIN)/setup-envtest
KUSTOMIZE ?= $(GOBIN)/kustomize
GOLANGCI_LINT ?= $(GOBIN)/golangci-lint-v2
ENVTEST_K8S_VERSION ?= 1.37.0
IMG ?= ghcr.io/mediactl/clustarr:dev
MEDIA_IMG ?= ghcr.io/mediactl/clustarr/media:dev
TRANSCODER_IMG ?= ghcr.io/mediactl/clustarr/transcoder:dev
TRANSCODER_CUDA_IMG ?= ghcr.io/mediactl/clustarr/transcoder-cuda:dev

API_PATHS := ./api/...
CRD_DIR := config/crd/bases

# The RBAC ClusterRoles `make manifests` generates, one per identity that runs
# under its own ServiceAccount -- design §10: "each service gets its own
# ClusterRole generated by controller-gen rbac markers next to each
# reconciler". Until task X14 every service shared one union
# clustarr-manager-role, so each service held every other service's grants
# (importarr's rootfolders update, grabarr's StatefulSet writes, indexarr's
# Secret creates ...) and no guard could tell a marker a service needs from
# one it merely inherited.
#
# Each role is generated from exactly the packages listed for it in
# RBAC_PATHS_<role>, and written to config/rbac/<role>_role.yaml (hyphens as
# underscores) as ClusterRole clustarr-<role>-role:
#
#   * a service's role reads every package under its directory, so a new
#     package that grows a marker is covered with no list to update;
#   * grabarr-engine is the one sub-identity that runs as separate pods under
#     its own ServiceAccount: the engine pods the DownloadClient controller
#     creates. Its role reads only its own packages, and grabarr's reads
#     everything under app/grab/ EXCEPT the engines -- the controller never
#     needs an engine's grants. The transcode pool Jobs cmd/squasharr-worker
#     runs are the other kind of per-pod workload, but carry no
#     ServiceAccount and so no role of their own: squasharr is the sole
#     writer of TranscodeJob.status, over NATS (X14), and app/squash/worker
#     holds no RBAC markers.
#
# cmd/clustarr's guards read RBAC_ROLES and RBAC_PATHS_* from here rather than
# restating them: TestEveryPackageWithRBACMarkersIsInARole fails when a
# package with markers is in no role, and the chart copies of every role are
# held byte-identical to these files by TestChartRBACMatchesTheGeneratedRoles.
RBAC_ROLES := catalogarr importarr indexarr grabarr grabarr-engine squasharr captionarr
RBAC_PATHS_catalogarr := ./app/catalog/...
RBAC_PATHS_importarr := ./app/import/...
RBAC_PATHS_indexarr := ./app/indexer/...
RBAC_PATHS_grabarr := ./app/grab ./app/grab/controller/... ./app/grab/status
RBAC_PATHS_grabarr-engine := ./app/grab/engine/... ./app/grab/status
RBAC_PATHS_squasharr := ./app/squash/...
RBAC_PATHS_captionarr := ./app/caption/...

.PHONY: all
all: generate manifests build

##@ Development

# controller-gen v0.22.0's applyconfiguration generator ignores output rules: it
# writes straight to disk at <pkg dir>/<kubebuilder:ac:output:package>, so no
# output:applyconfiguration:dir flag is passed below (it is silently discarded).
# Generation is opt-in per package via +kubebuilder:ac:generate=true and the
# destination is set per group by +kubebuilder:ac:output:package, both in each
# groupversion_info.go.
.PHONY: generate
generate: ## Generate DeepCopy and apply-configuration code.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="$(API_PATHS)"
	$(CONTROLLER_GEN) applyconfiguration:headerFile="hack/boilerplate.go.txt" paths="$(API_PATHS)"

# No templ binary is installed; `go run` against the version go.mod already
# pins (v0.3.1020) generates the same *_templ.go it would, without adding a
# tool dependency. The generated files are committed, so a generator change
# can never break a build unattended -- this target is for regenerating them
# after editing a .templ file, not a build-time step.
.PHONY: templ
templ: ## Regenerate ui/views/*_templ.go and ui/components/*/*_templ.go from their .templ sources.
	go run github.com/a-h/templ/cmd/templ@v0.3.1020 generate

# Tailwind's standalone CLI is a platform binary, not a Go module -- Phase G
# ruling R4 (docs/superpowers/plans/2026-09-23-phase-g-parity.md) is no Node
# and no new Go dependency for a CSS build step. Pinned to v4.3.3 (the
# standalone CLI's latest release as of 2026-09-23; there is no older LTS
# line to track) with a sha256 recorded per asset below, verified against
# that release's sha256sums.txt, so a corrupted or substituted download
# fails loudly instead of silently changing the CSS that ui/static.go later
# embeds. Like `templ`, this is a standalone target: `make build` never
# invokes it, and the output (ui/static/app.css) is committed so a build
# never needs the tailwindcss binary at all.
TAILWINDCSS_VERSION ?= 4.3.3
TAILWINDCSS ?= $(GOBIN)/tailwindcss-$(TAILWINDCSS_VERSION)
TAILWINDCSS_OS := $(shell go env GOOS)
TAILWINDCSS_ARCH := $(shell go env GOARCH)

# Maps GOOS/GOARCH to the asset name tailwindlabs/tailwindcss publishes at
# https://github.com/tailwindlabs/tailwindcss/releases/download/v$(TAILWINDCSS_VERSION)/<asset>
# and to that asset's sha256. Only the platforms this project is built and
# developed on are listed; an unlisted GOOS/GOARCH fails the target rather
# than fetching an unverified binary.
ifeq ($(TAILWINDCSS_OS)_$(TAILWINDCSS_ARCH),linux_amd64)
TAILWINDCSS_ASSET := tailwindcss-linux-x64
TAILWINDCSS_SHA256 := dc61b3ac6b8c9ca874c0cc4c57b2409791a64c5540404ca5f5367360babc313a
else ifeq ($(TAILWINDCSS_OS)_$(TAILWINDCSS_ARCH),linux_arm64)
TAILWINDCSS_ASSET := tailwindcss-linux-arm64
TAILWINDCSS_SHA256 := 55fd0b241214eff3de1e8ee4f22796662f2d2e7a49bcfca7477cfd0bac398195
else ifeq ($(TAILWINDCSS_OS)_$(TAILWINDCSS_ARCH),darwin_amd64)
TAILWINDCSS_ASSET := tailwindcss-macos-x64
TAILWINDCSS_SHA256 := 7922e0953f2110c05976e3bf58f14e643d90427575e766b7d433f5f80cbee7e1
else ifeq ($(TAILWINDCSS_OS)_$(TAILWINDCSS_ARCH),darwin_arm64)
TAILWINDCSS_ASSET := tailwindcss-macos-arm64
TAILWINDCSS_SHA256 := cdf646702987a743464dff4d9c60fd4480d1c1e73dd819a9a67f1078815dce9d
endif

.PHONY: css
css: ## Build ui/static/app.css with the standalone Tailwind CLI (downloads it into GOBIN if absent).
	@if [ -z "$(TAILWINDCSS_ASSET)" ]; then \
		echo "no pinned tailwindcss release asset for GOOS=$(TAILWINDCSS_OS) GOARCH=$(TAILWINDCSS_ARCH); add one to the Makefile"; \
		exit 1; \
	fi
	@if [ ! -x "$(TAILWINDCSS)" ]; then \
		echo "downloading tailwindcss v$(TAILWINDCSS_VERSION) ($(TAILWINDCSS_ASSET)) into $(TAILWINDCSS)"; \
		curl -fsSL -o "$(TAILWINDCSS).tmp" "https://github.com/tailwindlabs/tailwindcss/releases/download/v$(TAILWINDCSS_VERSION)/$(TAILWINDCSS_ASSET)"; \
		echo "$(TAILWINDCSS_SHA256)  $(TAILWINDCSS).tmp" | sha256sum -c -; \
		chmod +x "$(TAILWINDCSS).tmp"; \
		mv "$(TAILWINDCSS).tmp" "$(TAILWINDCSS)"; \
	fi
	$(TAILWINDCSS) -i ui/static/input.css -o ui/static/app.css -m

.PHONY: manifests
manifests: ## Generate CRDs and one RBAC ClusterRole per identity (RBAC_ROLES).
	$(CONTROLLER_GEN) crd paths="$(API_PATHS)" output:crd:artifacts:config=$(CRD_DIR)
	@mkdir -p config/rbac
	$(foreach role,$(RBAC_ROLES),$(CONTROLLER_GEN) rbac:roleName=clustarr-$(role)-role $(foreach p,$(RBAC_PATHS_$(role)),paths=$(p)) output:rbac:stdout > config/rbac/$(subst -,_,$(role))_role.yaml &&) true

.PHONY: fmt
fmt: ## Run gofmt.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet.
	go vet ./...

.PHONY: lint
lint: ## Run golangci-lint.
	$(GOLANGCI_LINT) run ./...

.PHONY: tidy
tidy: ## Tidy go.mod.
	go mod tidy

##@ Build

.PHONY: cardigann-bundle
cardigann-bundle: ## Re-pack .data/Definitions into the embedded Cardigann corpus (app/indexer/bundle/embedded).
	go run ./hack/pack-cardigann -src .data/Definitions -out app/indexer/bundle/embedded/definitions.zip


.PHONY: build
build: ## Build the clustarr binary.
	CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X github.com/mediactl/clustarr/pkg/version.Version=$(shell git describe --tags --always --dirty 2>/dev/null || echo dev)" -o bin/clustarr ./cmd/clustarr
	CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X github.com/mediactl/clustarr/pkg/version.Version=$(shell git describe --tags --always --dirty 2>/dev/null || echo dev)" -o bin/squasharr-worker ./cmd/squasharr-worker

.PHONY: docker-build
docker-build: ## Build controller, media and transcoder images.
	docker build -f images/Dockerfile.controller -t $(IMG) .
	docker build -f images/Dockerfile.media -t $(MEDIA_IMG) .
	docker build -f images/Dockerfile.transcoder --target transcoder -t $(TRANSCODER_IMG) .

.PHONY: docker-build-cuda
docker-build-cuda: ## Build the CUDA transcoder image (amd64).
	docker build -f images/Dockerfile.transcoder --target transcoder-cuda -t $(TRANSCODER_CUDA_IMG) .

##@ Test

.PHONY: test
# TEST_PARALLEL caps how many packages run at once. Around fifteen packages
# each stand up their own envtest control plane, and running them all together
# starves the apiservers: suites fail in a DIFFERENT package on each run, pass
# 3/3 in isolation, and read as a mystery flake rather than as contention.
# Raise it on a bigger machine; lower it if the flake reappears.
# Lower this if envtest suites start failing with "timeout waiting for process
# kube-apiserver to start". Each suite runs its own control plane, so the limit
# is the machine's, not the code's -- and the failure lands in a DIFFERENT
# package on each run, which reads as a mystery flake rather than as contention.
# 4 is comfortable on an idle machine; a box already running other clusters
# wants 2.
TEST_PARALLEL ?= 4

test-race: envtest ## Run the suites under the race detector.
	@mkdir -p "$${CLUSTARR_TEST_MEDIA_ROOT:-/data/media}" 2>/dev/null || true
	KUBEBUILDER_ASSETS="$(shell $(SETUP_ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test ./... -race -p $(TEST_PARALLEL)

test: envtest ## Run unit and envtest suites.
	@mkdir -p "$${CLUSTARR_TEST_MEDIA_ROOT:-/data/media}" 2>/dev/null || echo "warning: could not create $${CLUSTARR_TEST_MEDIA_ROOT:-/data/media}; importarr's scan suites will skip"
	KUBEBUILDER_ASSETS="$(shell $(SETUP_ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test ./... -p $(TEST_PARALLEL) -coverprofile cover.out

.PHONY: test-unit
test-unit: ## Run unit tests only (no envtest).
	go test -short ./...

.PHONY: envtest
envtest: ## Download envtest binaries.
	$(SETUP_ENVTEST) use $(ENVTEST_K8S_VERSION) -p path >/dev/null

# Extra arguments appended to the e2e `go test` invocation, e.g.
#   make e2e E2E_ARGS="-run TestLibraryRescan -v"
# hack/e2e.sh forwards its own E2E_ARGS through here rather than restating the
# go test line, so the script and this target cannot drift apart.
E2E_ARGS ?=

.PHONY: e2e
e2e: ## Run kind-based end-to-end tests. E2E_ARGS="-run ..." appends go test flags.
	go test ./test/e2e/... -tags e2e -timeout 30m $(E2E_ARGS)

##@ Deploy

.PHONY: install
install: manifests ## Install CRDs into the current cluster.
	$(KUSTOMIZE) build config/crd | kubectl apply --server-side -f -

.PHONY: uninstall
uninstall: manifests ## Remove CRDs from the current cluster.
	$(KUSTOMIZE) build config/crd | kubectl delete --ignore-not-found -f -

.PHONY: deploy
deploy: manifests ## Deploy controllers into the current cluster.
	$(KUSTOMIZE) build config/default | kubectl apply --server-side -f -

.PHONY: kind-up
kind-up: ## Create a local kind cluster with NATS.
	hack/kind.sh up

.PHONY: kind-down
kind-down:
	hack/kind.sh down

.PHONY: help
help:
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
