/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	transcodev1alpha1 "github.com/mediactl/clustarr/api/transcode/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AudioGraftStatusApplyConfiguration represents a declarative configuration of the AudioGraftStatus type for use
// with apply.
//
// AudioGraftStatus is squasharr's (ManagerSquasharr).
type AudioGraftStatusApplyConfiguration struct {
	ObservedGeneration *int64                             `json:"observedGeneration,omitempty"`
	Phase              *transcodev1alpha1.AudioGraftPhase `json:"phase,omitempty"`
	Reason             *string                            `json:"reason,omitempty"`
	Message            *string                            `json:"message,omitempty"`
	// MediaFileRef is the MediaFile the graft was judged against: the
	// item's file when this status was written.
	MediaFileRef *string `json:"mediaFileRef,omitempty"`
	// TargetProbeHash is that file's probe hash then; a Failed graft is
	// retried only for another hash or another generation.
	TargetProbeHash *string `json:"targetProbeHash,omitempty"`
	// JobName is the Job of the current attempt: a graft or reduce Job, or
	// "transcodejob/<name>" for a graft riding along with that transcode.
	JobName *string `json:"jobName,omitempty"`
	// DonorAudioPath is the donor reduced to its audio (<stem>.mka), which
	// every graft reads; empty until the reduce Job has run.
	DonorAudioPath *string `json:"donorAudioPath,omitempty"`
	// RateName is the donor's speed against the target ("1", "25/23.976");
	// RateMicros the refined rate in millionths.
	RateName   *string `json:"rateName,omitempty"`
	RateMicros *int64  `json:"rateMicros,omitempty"`
	// RateMarginMilli is the chosen rate's margin over the runner-up, in
	// thousandths (2030 = 2.03).
	RateMarginMilli *int32 `json:"rateMarginMilli,omitempty"`
	// CoveragePercent is the share of the target the confident windows
	// cover.
	CoveragePercent *int32                                `json:"coveragePercent,omitempty"`
	Segments        []AudioGraftSegmentApplyConfiguration `json:"segments,omitempty"`
	// ResidualMillis is the verify pass's median residual offset, and
	// Within80Percent its share of windows within 80 ms.
	ResidualMillis  *int32 `json:"residualMillis,omitempty"`
	Within80Percent *int32 `json:"within80Percent,omitempty"`
	// GraftTag is the CLUSTARR_GRAFT tag the grafted file carries.
	GraftTag    *string  `json:"graftTag,omitempty"`
	StartedAt   *v1.Time `json:"startedAt,omitempty"`
	CompletedAt *v1.Time `json:"completedAt,omitempty"`
	// RejectedReleases are donor releases a graft failed with: the donor
	// search never takes them again for this item (spec §9).
	RejectedReleases []string                             `json:"rejectedReleases,omitempty"`
	Conditions       []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// AudioGraftStatusApplyConfiguration constructs a declarative configuration of the AudioGraftStatus type for use with
// apply.
func AudioGraftStatus() *AudioGraftStatusApplyConfiguration {
	return &AudioGraftStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithObservedGeneration(value int64) *AudioGraftStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithPhase(value transcodev1alpha1.AudioGraftPhase) *AudioGraftStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithReason(value string) *AudioGraftStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithMessage(value string) *AudioGraftStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithMediaFileRef sets the MediaFileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaFileRef field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithMediaFileRef(value string) *AudioGraftStatusApplyConfiguration {
	b.MediaFileRef = &value
	return b
}

// WithTargetProbeHash sets the TargetProbeHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetProbeHash field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithTargetProbeHash(value string) *AudioGraftStatusApplyConfiguration {
	b.TargetProbeHash = &value
	return b
}

// WithJobName sets the JobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobName field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithJobName(value string) *AudioGraftStatusApplyConfiguration {
	b.JobName = &value
	return b
}

// WithDonorAudioPath sets the DonorAudioPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DonorAudioPath field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithDonorAudioPath(value string) *AudioGraftStatusApplyConfiguration {
	b.DonorAudioPath = &value
	return b
}

// WithRateName sets the RateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateName field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithRateName(value string) *AudioGraftStatusApplyConfiguration {
	b.RateName = &value
	return b
}

// WithRateMicros sets the RateMicros field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateMicros field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithRateMicros(value int64) *AudioGraftStatusApplyConfiguration {
	b.RateMicros = &value
	return b
}

// WithRateMarginMilli sets the RateMarginMilli field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateMarginMilli field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithRateMarginMilli(value int32) *AudioGraftStatusApplyConfiguration {
	b.RateMarginMilli = &value
	return b
}

// WithCoveragePercent sets the CoveragePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CoveragePercent field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithCoveragePercent(value int32) *AudioGraftStatusApplyConfiguration {
	b.CoveragePercent = &value
	return b
}

// WithSegments adds the given value to the Segments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Segments field.
func (b *AudioGraftStatusApplyConfiguration) WithSegments(values ...*AudioGraftSegmentApplyConfiguration) *AudioGraftStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSegments")
		}
		b.Segments = append(b.Segments, *values[i])
	}
	return b
}

// WithResidualMillis sets the ResidualMillis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResidualMillis field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithResidualMillis(value int32) *AudioGraftStatusApplyConfiguration {
	b.ResidualMillis = &value
	return b
}

// WithWithin80Percent sets the Within80Percent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Within80Percent field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithWithin80Percent(value int32) *AudioGraftStatusApplyConfiguration {
	b.Within80Percent = &value
	return b
}

// WithGraftTag sets the GraftTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GraftTag field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithGraftTag(value string) *AudioGraftStatusApplyConfiguration {
	b.GraftTag = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithStartedAt(value v1.Time) *AudioGraftStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithCompletedAt sets the CompletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletedAt field is set to the value of the last call.
func (b *AudioGraftStatusApplyConfiguration) WithCompletedAt(value v1.Time) *AudioGraftStatusApplyConfiguration {
	b.CompletedAt = &value
	return b
}

// WithRejectedReleases adds the given value to the RejectedReleases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RejectedReleases field.
func (b *AudioGraftStatusApplyConfiguration) WithRejectedReleases(values ...string) *AudioGraftStatusApplyConfiguration {
	for i := range values {
		b.RejectedReleases = append(b.RejectedReleases, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AudioGraftStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *AudioGraftStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
