/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	transcodev1alpha1 "github.com/mediactl/clustarr/api/transcode/v1alpha1"
)

// EncoderLimitApplyConfiguration represents a declarative configuration of the EncoderLimit type for use
// with apply.
//
// EncoderLimit is one GPU node's measured encoder device limits.
type EncoderLimitApplyConfiguration struct {
	// Class is the hardware class of the node's pool.
	Class *transcodev1alpha1.Hardware `json:"class,omitempty"`
	// Node is the node the limits were measured on.
	Node *string `json:"node,omitempty"`
	// MaxBFrames is the most B-frames the device encodes, when a profile
	// asked for more; absent is no limit known.
	MaxBFrames *int32 `json:"maxBFrames,omitempty"`
	// MaxLookahead is the deepest rate-control lookahead the device uses,
	// when a profile asked for more; absent is no limit known.
	MaxLookahead *int32 `json:"maxLookahead,omitempty"`
}

// EncoderLimitApplyConfiguration constructs a declarative configuration of the EncoderLimit type for use with
// apply.
func EncoderLimit() *EncoderLimitApplyConfiguration {
	return &EncoderLimitApplyConfiguration{}
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *EncoderLimitApplyConfiguration) WithClass(value transcodev1alpha1.Hardware) *EncoderLimitApplyConfiguration {
	b.Class = &value
	return b
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *EncoderLimitApplyConfiguration) WithNode(value string) *EncoderLimitApplyConfiguration {
	b.Node = &value
	return b
}

// WithMaxBFrames sets the MaxBFrames field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxBFrames field is set to the value of the last call.
func (b *EncoderLimitApplyConfiguration) WithMaxBFrames(value int32) *EncoderLimitApplyConfiguration {
	b.MaxBFrames = &value
	return b
}

// WithMaxLookahead sets the MaxLookahead field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxLookahead field is set to the value of the last call.
func (b *EncoderLimitApplyConfiguration) WithMaxLookahead(value int32) *EncoderLimitApplyConfiguration {
	b.MaxLookahead = &value
	return b
}
