/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	transcodev1alpha1 "github.com/mediactl/clustarr/api/transcode/v1alpha1"
)

// HDRSpecApplyConfiguration represents a declarative configuration of the HDRSpec type for use
// with apply.
//
// HDRSpec describes how high-dynamic-range metadata is handled.
type HDRSpecApplyConfiguration struct {
	// HDR10Plus says what happens to HDR10+ dynamic metadata.
	HDR10Plus *transcodev1alpha1.HDR10PlusMode `json:"hdr10Plus,omitempty"`
	// DolbyVision says what happens to Dolby Vision sources.
	DolbyVision *transcodev1alpha1.DolbyVisionMode `json:"dolbyVision,omitempty"`
}

// HDRSpecApplyConfiguration constructs a declarative configuration of the HDRSpec type for use with
// apply.
func HDRSpec() *HDRSpecApplyConfiguration {
	return &HDRSpecApplyConfiguration{}
}

// WithHDR10Plus sets the HDR10Plus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HDR10Plus field is set to the value of the last call.
func (b *HDRSpecApplyConfiguration) WithHDR10Plus(value transcodev1alpha1.HDR10PlusMode) *HDRSpecApplyConfiguration {
	b.HDR10Plus = &value
	return b
}

// WithDolbyVision sets the DolbyVision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DolbyVision field is set to the value of the last call.
func (b *HDRSpecApplyConfiguration) WithDolbyVision(value transcodev1alpha1.DolbyVisionMode) *HDRSpecApplyConfiguration {
	b.DolbyVision = &value
	return b
}
