/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PolicySpecApplyConfiguration represents a declarative configuration of the PolicySpec type for use
// with apply.
//
// PolicySpec decides which files are transcoded and what happens afterwards.
type PolicySpecApplyConfiguration struct {
	// SkipIfCompliant skips files that already satisfy the profile. A pointer so
	// a Go client can send an explicit false; unset means true.
	SkipIfCompliant *bool `json:"skipIfCompliant,omitempty"`
	// RemuxOnlyWhenVideoCompliant only remuxes (no video encode) when the video
	// stream already satisfies the profile. A pointer so a Go client can send an
	// explicit false; unset means true.
	RemuxOnlyWhenVideoCompliant *bool `json:"remuxOnlyWhenVideoCompliant,omitempty"`
	// NeverTranscodeModifiers lists quality modifiers (see common Modifier)
	// whose files are never transcoded.
	NeverTranscodeModifiers []string `json:"neverTranscodeModifiers,omitempty"`
	// MinDuration is the shortest source runtime considered for transcoding;
	// "0s" considers every file. A pointer because zero is meaningful: a Go
	// client always sends a non-pointer Duration, so the 1m default would
	// never reach a profile created from Go. Unset means 1m.
	MinDuration *v1.Duration `json:"minDuration,omitempty"`
	// MaxOutputToSourcePercent fails a job whose output is larger than this
	// percentage of the source size: 100 (the default) refuses any output
	// bigger than the file it replaces, 150 allows half as large again. It is
	// the design spec's MaxOutputToSourceRatio 1.0 as a scaled integer, since
	// the API carries no floats. 0 disables the check. A pointer so a Go
	// client can send that 0: with omitempty it would be dropped and
	// defaulted back to 100. Unset means 100.
	MaxOutputToSourcePercent *int32 `json:"maxOutputToSourcePercent,omitempty"`
	// ReplaceSource replaces the source file with the output on success;
	// false leaves the source file in place instead of renaming the output
	// over it. A pointer so a Go client can send an explicit false; unset
	// means true.
	ReplaceSource *bool `json:"replaceSource,omitempty"`
	// RecycleBin keeps the replaced source in the root folder's recycle bin.
	// false lets the swap drop the library's link to it outright (a seeding
	// hard link elsewhere under /data keeps its own copy either way). A
	// pointer so a Go client can send an explicit false; unset means true.
	RecycleBin *bool `json:"recycleBin,omitempty"`
}

// PolicySpecApplyConfiguration constructs a declarative configuration of the PolicySpec type for use with
// apply.
func PolicySpec() *PolicySpecApplyConfiguration {
	return &PolicySpecApplyConfiguration{}
}

// WithSkipIfCompliant sets the SkipIfCompliant field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipIfCompliant field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithSkipIfCompliant(value bool) *PolicySpecApplyConfiguration {
	b.SkipIfCompliant = &value
	return b
}

// WithRemuxOnlyWhenVideoCompliant sets the RemuxOnlyWhenVideoCompliant field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemuxOnlyWhenVideoCompliant field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithRemuxOnlyWhenVideoCompliant(value bool) *PolicySpecApplyConfiguration {
	b.RemuxOnlyWhenVideoCompliant = &value
	return b
}

// WithNeverTranscodeModifiers adds the given value to the NeverTranscodeModifiers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NeverTranscodeModifiers field.
func (b *PolicySpecApplyConfiguration) WithNeverTranscodeModifiers(values ...string) *PolicySpecApplyConfiguration {
	for i := range values {
		b.NeverTranscodeModifiers = append(b.NeverTranscodeModifiers, values[i])
	}
	return b
}

// WithMinDuration sets the MinDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinDuration field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithMinDuration(value v1.Duration) *PolicySpecApplyConfiguration {
	b.MinDuration = &value
	return b
}

// WithMaxOutputToSourcePercent sets the MaxOutputToSourcePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxOutputToSourcePercent field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithMaxOutputToSourcePercent(value int32) *PolicySpecApplyConfiguration {
	b.MaxOutputToSourcePercent = &value
	return b
}

// WithReplaceSource sets the ReplaceSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplaceSource field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithReplaceSource(value bool) *PolicySpecApplyConfiguration {
	b.ReplaceSource = &value
	return b
}

// WithRecycleBin sets the RecycleBin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecycleBin field is set to the value of the last call.
func (b *PolicySpecApplyConfiguration) WithRecycleBin(value bool) *PolicySpecApplyConfiguration {
	b.RecycleBin = &value
	return b
}
