/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ProgressApplyConfiguration represents a declarative configuration of the Progress type for use
// with apply.
//
// Progress is the worker's encode progress, patched at most every 10 s.
type ProgressApplyConfiguration struct {
	// Percent is the completed percentage of the encode, 0-100.
	Percent *int32 `json:"percent,omitempty"`
	// Frame is the last encoded frame number.
	Frame *int64 `json:"frame,omitempty"`
	// FPSMilli is the current encode rate in thousandths of a frame per second.
	FPSMilli *int32 `json:"fpsMilli,omitempty"`
	// SpeedMilli is the encode speed relative to real time, in thousandths,
	// so 1.5x real time is 1500.
	SpeedMilli *int32 `json:"speedMilli,omitempty"`
	// OutTimeMillis is the output timestamp reached so far, in milliseconds.
	OutTimeMillis *int64 `json:"outTimeMillis,omitempty"`
	// BitrateKbps is the current output bitrate in whole kilobits per second.
	BitrateKbps *int32 `json:"bitrateKbps,omitempty"`
	// UpdatedAt is when this progress was reported.
	UpdatedAt *v1.Time `json:"updatedAt,omitempty"`
}

// ProgressApplyConfiguration constructs a declarative configuration of the Progress type for use with
// apply.
func Progress() *ProgressApplyConfiguration {
	return &ProgressApplyConfiguration{}
}

// WithPercent sets the Percent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Percent field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithPercent(value int32) *ProgressApplyConfiguration {
	b.Percent = &value
	return b
}

// WithFrame sets the Frame field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Frame field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithFrame(value int64) *ProgressApplyConfiguration {
	b.Frame = &value
	return b
}

// WithFPSMilli sets the FPSMilli field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FPSMilli field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithFPSMilli(value int32) *ProgressApplyConfiguration {
	b.FPSMilli = &value
	return b
}

// WithSpeedMilli sets the SpeedMilli field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpeedMilli field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithSpeedMilli(value int32) *ProgressApplyConfiguration {
	b.SpeedMilli = &value
	return b
}

// WithOutTimeMillis sets the OutTimeMillis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutTimeMillis field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithOutTimeMillis(value int64) *ProgressApplyConfiguration {
	b.OutTimeMillis = &value
	return b
}

// WithBitrateKbps sets the BitrateKbps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitrateKbps field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithBitrateKbps(value int32) *ProgressApplyConfiguration {
	b.BitrateKbps = &value
	return b
}

// WithUpdatedAt sets the UpdatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedAt field is set to the value of the last call.
func (b *ProgressApplyConfiguration) WithUpdatedAt(value v1.Time) *ProgressApplyConfiguration {
	b.UpdatedAt = &value
	return b
}
