/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SubSpecApplyConfiguration represents a declarative configuration of the SubSpec type for use
// with apply.
//
// SubSpec describes how subtitle tracks and attachments are handled.
type SubSpecApplyConfiguration struct {
	// CopyText copies text-based subtitle tracks. A pointer so a Go client can
	// send an explicit false; unset means true.
	CopyText *bool `json:"copyText,omitempty"`
	// CopyBitmap copies bitmap (PGS/VobSub) subtitle tracks. A pointer so a Go
	// client can send an explicit false; unset means true.
	CopyBitmap *bool `json:"copyBitmap,omitempty"`
	// CopyAttachments copies container attachments such as fonts. A pointer so a
	// Go client can send an explicit false; unset means true.
	CopyAttachments *bool `json:"copyAttachments,omitempty"`
}

// SubSpecApplyConfiguration constructs a declarative configuration of the SubSpec type for use with
// apply.
func SubSpec() *SubSpecApplyConfiguration {
	return &SubSpecApplyConfiguration{}
}

// WithCopyText sets the CopyText field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CopyText field is set to the value of the last call.
func (b *SubSpecApplyConfiguration) WithCopyText(value bool) *SubSpecApplyConfiguration {
	b.CopyText = &value
	return b
}

// WithCopyBitmap sets the CopyBitmap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CopyBitmap field is set to the value of the last call.
func (b *SubSpecApplyConfiguration) WithCopyBitmap(value bool) *SubSpecApplyConfiguration {
	b.CopyBitmap = &value
	return b
}

// WithCopyAttachments sets the CopyAttachments field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CopyAttachments field is set to the value of the last call.
func (b *SubSpecApplyConfiguration) WithCopyAttachments(value bool) *SubSpecApplyConfiguration {
	b.CopyAttachments = &value
	return b
}
