/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Package downloadclient reconciles DownloadClient (ADR-0019 §6.7): it
// stands up the engine workload the client describes, ensures one durable
// per rendered engine ordinal (grabarr-engine-<client>-<ordinal>, §5.1) and
// deletes a scaled-away ordinal's once nothing is pinned to it, and reports
// the client from its engines' own records: active, queued, seeding, the
// engines' free bytes (DiskSpaceOK), EngineReady (ready replicas AND a fresh
// engine record saying ready), ProxyUDPUnavailable and the unidentified
// transfers. After a clustarr-transfers loss it asks every engine for a
// resync at a new status.resyncSeq, and it commands the removal, bytes
// kept, of a transfer an engine holds with no claim once its grace passed.
// The Download watch, the blocklist sweeper (the release index sweeps its
// own rows, §6.14) and the manager's own statfs are gone.
//
// # DiskSpaceOK has no spec field to read a floor from
//
// Unlike RootFolderSpec.MinFreeBytes, DownloadClientSpec carries no
// minimum-free-space field (verified against downloadclient_types.go). This
// package therefore invents one -- [DefaultMinFreeBytes], overridable on
// [Reconciler] -- the same way app/catalog/controller/rootfolder invented its
// recheckInterval: cheap, frequent enough, and documented so a later task can
// replace it with a real signal (a RootFolder-style spec field, or a cheaper
// kubelet volume metric) without archaeology.
//
// # What this package deliberately does not build
//
// No Service and no hostPort for the torrent engine's peer-facing port
// (spec §6.3 lists "hostPort/Service for ListenPort" as part of the torrent
// engine's eventual shape). Peer connectivity is a networking concern for
// whichever task wires the engine's actual listener; standing up a Service
// with no engine behind it yet would be dead configuration. The container
// port is still declared on the pod so that task has something to point a
// Service at.
//
// No per-provider Secret validation for usenet clients (unlike
// indexerproxy's existence check on spec.secretRef). DiskSpaceOK and
// EngineReady are the two conditions this task owns; a client whose
// NNTPProvider secrets are wrong will simply fail to connect once an engine
// exists to try, and that failure belongs to the engine (D2-2/D2-6), not to
// this reconciler.
//
// # R5 -- this task turns automatic search on
//
// app/catalog/worker/search/worker.go's enabledProtocols already lists live
// DownloadClient objects and fails closed for a protocol with no enabled
// client (verified at worker.go:498-527). Nothing in this package changes
// that code, and nothing needs to: creating a DownloadClient CR was already
// possible before this task landed, but pointless, because nothing reconciled
// it. The moment a reconciler exists to make a DownloadClient mean something
// -- a real engine workload, a real Ready condition -- the first enabled
// client an operator or an e2e fixture creates flips enabledProtocols() from
// empty to non-empty for that protocol, and automatic search, previously
// inert, starts grabbing.
//
// # The RBAC markers below are package-level comments
//
// controller-gen only collects +kubebuilder:rbac from a comment group that is
// not attached to a declaration -- a blank line above the `package` clause
// keeps this one package-level. cmd/clustarr's TestRBACMarkersArePackageLevel
// is the guard; four catalogarr controllers shipped with none of their
// permissions reached because their markers sat directly above
// SetupWithManager instead.
//
// app/grab/status/doc.go already grants downloads and downloads/status
// get;list;watch;update;patch for the Download controller (D2-4) and the
// engines; this package adds delete on downloads, for the sweep, and get,
// list, watch, update and patch are re-declared here too because this
// package's own Reconcile lists Downloads for the Active/Queued/Seeding
// rollup -- a marker states what the package it sits in does, not what is
// already granted somewhere else in the tree, so a working permission set
// does not depend on two packages happening to land in the right order.
//
// config/rbac/role.yaml is NOT regenerated by this task -- Makefile's
// RBAC_DIRS already lists grabarr, so `make manifests` will pick these up,
// but running it is task D2-8's job (see the task instructions). Until then
// cmd/clustarr's TestGeneratedRoleCoversEveryStatusWriter is expected to fail
// on download.clustarr.io/downloadclients/status, exactly as
// app/grab/status/doc.go's own comment predicts for downloadclients, the
// engine StatefulSet and the blocklist sweep.
//
// +kubebuilder:rbac:groups=download.clustarr.io,resources=downloadclients,verbs=get;list;watch
// +kubebuilder:rbac:groups=download.clustarr.io,resources=downloadclients/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=apps,resources=statefulsets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch
// +kubebuilder:rbac:groups="",resources=persistentvolumeclaims,verbs=get;list;watch;create;update;patch
// +kubebuilder:rbac:groups=events.k8s.io,resources=events,verbs=create;patch
//
// The usenet engine's provider Secrets are read by name, get alone, to fold
// their data into the engine's config hash. They are deliberately not
// watched: list and watch cannot be narrowed in RBAC, and would let grabarr
// enumerate every Secret in its scope.
//
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get
package downloadclient
