/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package transcode

import (
	internal "github.com/mediactl/clustarr/api/applyconfiguration/transcode/internal"
	transcodev1alpha1 "github.com/mediactl/clustarr/api/applyconfiguration/transcode/transcode/v1alpha1"
	v1alpha1 "github.com/mediactl/clustarr/api/transcode/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=transcode.clustarr.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AudioPlan"):
		return &transcodev1alpha1.AudioPlanApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("AudioSpec"):
		return &transcodev1alpha1.AudioSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ChunkSpec"):
		return &transcodev1alpha1.ChunkSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CRFTable"):
		return &transcodev1alpha1.CRFTableApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GPUSpec"):
		return &transcodev1alpha1.GPUSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HDRSpec"):
		return &transcodev1alpha1.HDRSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NVENCSpec"):
		return &transcodev1alpha1.NVENCSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Plan"):
		return &transcodev1alpha1.PlanApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PolicySpec"):
		return &transcodev1alpha1.PolicySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Progress"):
		return &transcodev1alpha1.ProgressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("QSVSpec"):
		return &transcodev1alpha1.QSVSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Result"):
		return &transcodev1alpha1.ResultApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubSpec"):
		return &transcodev1alpha1.SubSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeJob"):
		return &transcodev1alpha1.TranscodeJobApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeJobSpec"):
		return &transcodev1alpha1.TranscodeJobSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeJobStatus"):
		return &transcodev1alpha1.TranscodeJobStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeProfile"):
		return &transcodev1alpha1.TranscodeProfileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeProfileSpec"):
		return &transcodev1alpha1.TranscodeProfileSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TranscodeProfileStatus"):
		return &transcodev1alpha1.TranscodeProfileStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VerifySpec"):
		return &transcodev1alpha1.VerifySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VideoSpec"):
		return &transcodev1alpha1.VideoSpecApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
