---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustarr-catalogarr-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - albums
  - books
  - episodes
  - issues
  - mediafiles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - albums/finalizers
  - artists/finalizers
  - audiobooks/finalizers
  - authors/finalizers
  - books/finalizers
  - comics/finalizers
  - episodes/finalizers
  - issues/finalizers
  - movies/finalizers
  - series/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - albums/status
  - artists/status
  - audiobooks/status
  - authors/status
  - books/status
  - comics/status
  - delayprofiles/status
  - episodes/status
  - issues/status
  - mediafiles/status
  - metadataproviders/status
  - movies/status
  - qualityprofiles/status
  - rootfolders/status
  - searches/status
  - series/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - artists
  - audiobooks
  - authors
  - comics
  - movies
  - searches
  - series
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - delayprofiles
  - metadataproviders
  - rootfolders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - importlists
  - libraryscans
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - qualityprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloadclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloads
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - index.clustarr.io
  resources:
  - indexers
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - subtitle.clustarr.io
  resources:
  - subtitlerequests
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - transcode.clustarr.io
  resources:
  - transcodejobs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - transcode.clustarr.io
  resources:
  - transcodeprofiles
  verbs:
  - get
  - list
  - watch
