---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustarr-grabarr-engine-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - download.clustarr.io
  resources:
  - downloadclients
  verbs:
  - get
  - list
  - watch
