---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustarr-manager-role
rules:
- apiGroups:
  - catalog.clustarr.io
  resources:
  - delayprofiles
  - mediafiles
  - qualityprofiles
  - rootfolders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - episodes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - episodes/finalizers
  - movies/finalizers
  - series/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - episodes/status
  - movies/status
  - searches/status
  - series/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - movies
  - searches
  - series
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloadclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloads
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - index.clustarr.io
  resources:
  - indexers
  verbs:
  - get
  - list
  - watch
