---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustarr-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - delayprofiles
  - metadataproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - delayprofiles/status
  - episodes/status
  - importexclusions/status
  - libraryscans/status
  - mediafiles/status
  - metadataproviders/status
  - movies/status
  - qualityprofiles/status
  - rootfolders/status
  - searches/status
  - series/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - episodes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - episodes/finalizers
  - importexclusions/finalizers
  - movies/finalizers
  - series/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.clustarr.io
  resources:
  - importexclusions
  - rootfolders
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - libraryscans
  - mediafiles
  - movies
  - searches
  - series
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.clustarr.io
  resources:
  - qualityprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloadclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - download.clustarr.io
  resources:
  - downloadclients/status
  - downloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - download.clustarr.io
  resources:
  - downloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - index.clustarr.io
  resources:
  - indexerdefinitions
  - indexerproxies
  - indexers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - index.clustarr.io
  resources:
  - indexerdefinitions/status
  - indexerproxies/status
  - indexers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - subtitle.clustarr.io
  resources:
  - subtitlerequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - transcode.clustarr.io
  resources:
  - transcodejobs
  - transcodeprofiles
  verbs:
  - get
  - list
  - watch
