---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustarr-squasharr-worker-role
rules:
- apiGroups:
  - catalog.clustarr.io
  resources:
  - mediafiles
  verbs:
  - get
- apiGroups:
  - catalog.clustarr.io
  resources:
  - rootfolders
  verbs:
  - list
- apiGroups:
  - transcode.clustarr.io
  resources:
  - transcodejobs
  - transcodeprofiles
  verbs:
  - get
- apiGroups:
  - transcode.clustarr.io
  resources:
  - transcodejobs/status
  verbs:
  - patch
