/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/mediactl/clustarr/api/common/v1alpha1"
	indexv1alpha1 "github.com/mediactl/clustarr/api/index/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IndexerDefinitionStatusApplyConfiguration represents a declarative configuration of the IndexerDefinitionStatus type for use
// with apply.
//
// IndexerDefinitionStatus defines the observed state of IndexerDefinition.
type IndexerDefinitionStatusApplyConfiguration struct {
	// ObservedGeneration is the most recent generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the definition's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ID is the Cardigann definition id parsed from spec.yaml.
	ID *string `json:"id,omitempty"`
	// Name is the human-readable indexer name parsed from spec.yaml.
	Name *string `json:"name,omitempty"`
	// Language is the definition's primary language (e.g. en-US).
	Language *string `json:"language,omitempty"`
	// Type is the privacy class of the definition.
	Type *indexv1alpha1.DefinitionType `json:"type,omitempty"`
	// Protocol is the transfer protocol the definition serves.
	Protocol *commonv1alpha1.Protocol `json:"protocol,omitempty"`
	// Sha256 is the hex digest of spec.yaml as last validated.
	Sha256 *string `json:"sha256,omitempty"`
	// Caps summarises the search modes and categories the definition supports.
	Caps *CapsSummaryApplyConfiguration `json:"caps,omitempty"`
}

// IndexerDefinitionStatusApplyConfiguration constructs a declarative configuration of the IndexerDefinitionStatus type for use with
// apply.
func IndexerDefinitionStatus() *IndexerDefinitionStatusApplyConfiguration {
	return &IndexerDefinitionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *IndexerDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *IndexerDefinitionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *IndexerDefinitionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithID(value string) *IndexerDefinitionStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithName(value string) *IndexerDefinitionStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithLanguage sets the Language field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Language field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithLanguage(value string) *IndexerDefinitionStatusApplyConfiguration {
	b.Language = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithType(value indexv1alpha1.DefinitionType) *IndexerDefinitionStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithProtocol(value commonv1alpha1.Protocol) *IndexerDefinitionStatusApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithSha256 sets the Sha256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha256 field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithSha256(value string) *IndexerDefinitionStatusApplyConfiguration {
	b.Sha256 = &value
	return b
}

// WithCaps sets the Caps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Caps field is set to the value of the last call.
func (b *IndexerDefinitionStatusApplyConfiguration) WithCaps(value *CapsSummaryApplyConfiguration) *IndexerDefinitionStatusApplyConfiguration {
	b.Caps = value
	return b
}
