/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	indexv1alpha1 "github.com/mediactl/clustarr/api/index/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IndexerProxySpecApplyConfiguration represents a declarative configuration of the IndexerProxySpec type for use
// with apply.
//
// IndexerProxySpec defines the desired state of IndexerProxy.
type IndexerProxySpecApplyConfiguration struct {
	// Type is the kind of proxy.
	Type *indexv1alpha1.IndexerProxyType `json:"type,omitempty"`
	// Host is the proxy hostname or IP address.
	Host *string `json:"host,omitempty"`
	// Port is the proxy port. It is required and has no default: a proxy is
	// addressed as host:port, and the defensible values are per-type
	// (flaresolverr 8191, http 3128/8080/8888, socks 1080), so any one
	// default would probe an endpoint nobody configured and report it Ready.
	// Before this was +required the CRD accepted a portless proxy that the
	// controller then always refused as an invalid spec.
	Port *int32 `json:"port,omitempty"`
	// SecretRef names a Secret in the same namespace holding proxy credentials.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// RequestTimeout is how long a request through the proxy may take. A Go
	// client always sends a Duration, so the prober floors a zero (or
	// negative) one to this default: a probe that may never return is never
	// meant.
	RequestTimeout *metav1.Duration `json:"requestTimeout,omitempty"`
	// Selector matches the Indexers (by label) that use this proxy. An empty
	// selector matches no Indexer: a Go client always sends {}, so "{}
	// matches everything" would route a whole namespace. An Indexer's own
	// spec.proxyRef wins over any selector. At most one http, socks4 or
	// socks5 proxy and at most one FlareSolverr may apply to an Indexer, and
	// the FlareSolverr is applied last; anything more, or a FlareSolverr
	// beside a proxy with credentials, fails closed (indexarr/proxy).
	Selector *applyconfigurationsmetav1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
}

// IndexerProxySpecApplyConfiguration constructs a declarative configuration of the IndexerProxySpec type for use with
// apply.
func IndexerProxySpec() *IndexerProxySpecApplyConfiguration {
	return &IndexerProxySpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithType(value indexv1alpha1.IndexerProxyType) *IndexerProxySpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithHost(value string) *IndexerProxySpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithPort(value int32) *IndexerProxySpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *IndexerProxySpecApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithRequestTimeout sets the RequestTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestTimeout field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithRequestTimeout(value metav1.Duration) *IndexerProxySpecApplyConfiguration {
	b.RequestTimeout = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *IndexerProxySpecApplyConfiguration) WithSelector(value *applyconfigurationsmetav1.LabelSelectorApplyConfiguration) *IndexerProxySpecApplyConfiguration {
	b.Selector = value
	return b
}
