/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/mediactl/clustarr/api/common/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IndexerSpecApplyConfiguration represents a declarative configuration of the IndexerSpec type for use
// with apply.
//
// IndexerSpec defines the desired state of Indexer.
type IndexerSpecApplyConfiguration struct {
	// Definition is the id of a bundled Cardigann definition, e.g. "1337x".
	Definition *string `json:"definition,omitempty"`
	// DefinitionRef is the name of an IndexerDefinition to use.
	DefinitionRef *string `json:"definitionRef,omitempty"`
	// Generic configures a plain Newznab/Torznab upstream.
	Generic *GenericNewznabApplyConfiguration `json:"generic,omitempty"`
	// BaseURL is the indexer's base URL.
	BaseURL *string `json:"baseURL,omitempty"`
	// Enabled turns the indexer on or off without deleting it.
	Enabled *bool `json:"enabled,omitempty"`
	// Priority orders indexers when the same release is offered by several; lower wins.
	Priority *int32 `json:"priority,omitempty"`
	// Settings holds the non-secret Cardigann settings for the definition.
	Settings map[string]string `json:"settings,omitempty"`
	// SecretRef names a Secret in the same namespace holding secret settings.
	// Recognised keys: apikey, username, password, cookie, passkey, rss_key.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// EnableRss allows the indexer to be polled for new releases.
	EnableRss *bool `json:"enableRss,omitempty"`
	// EnableAutomaticSearch allows the indexer to be used by automatic searches.
	EnableAutomaticSearch *bool `json:"enableAutomaticSearch,omitempty"`
	// EnableInteractiveSearch allows the indexer to be used by interactive searches.
	EnableInteractiveSearch *bool `json:"enableInteractiveSearch,omitempty"`
	// RssInterval is how often the RSS feed is polled. A Go client always
	// sends a Duration, so the RSS worker floors a zero (or negative) one to
	// this default: nobody means to poll an indexer infinitely often.
	RssInterval *metav1.Duration `json:"rssInterval,omitempty"`
	// Limits caps queries and grabs per window.
	Limits *LimitsApplyConfiguration `json:"limits,omitempty"`
	// RequestDelay is the minimum delay between requests to the indexer. It
	// is raised to the definition's requestDelay when that is larger. "0s"
	// is a supported "do not pace this indexer", so this is a pointer rather
	// than floored: a Go client always sends a non-pointer Duration, and the
	// 2s default would never reach an Indexer created from Go. Unset means 2s.
	RequestDelay *metav1.Duration `json:"requestDelay,omitempty"`
	// Timeout is the per-request HTTP timeout. A Go client always sends a
	// Duration, so every consumer floors a zero (or negative) one to this
	// default: a request that may never time out is never meant.
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// ProxyRef names an IndexerProxy in the same namespace to route requests through.
	ProxyRef *string `json:"proxyRef,omitempty"`
	// Categories are the Newznab category ids to search.
	Categories []int32 `json:"categories,omitempty"`
	// AnimeCategories are the Newznab category ids to search for anime.
	AnimeCategories []int32 `json:"animeCategories,omitempty"`
	// AnimeStandardFormatSearch also searches anime using standard SxxEyy numbering.
	AnimeStandardFormatSearch *bool `json:"animeStandardFormatSearch,omitempty"`
	// MinimumSeeders is the fewest seeders a torrent release may have to be considered.
	MinimumSeeders *int32 `json:"minimumSeeders,omitempty"`
	// SeedCriteria overrides the download client's seeding limits for releases from this indexer.
	SeedCriteria *commonv1alpha1.SeedCriteria `json:"seedCriteria,omitempty"`
	// DownloadClientRef names the DownloadClient to send grabs from this indexer to.
	DownloadClientRef *string `json:"downloadClientRef,omitempty"`
	// Tags are free-form labels used to match the indexer to catalog items.
	Tags []string `json:"tags,omitempty"`
}

// IndexerSpecApplyConfiguration constructs a declarative configuration of the IndexerSpec type for use with
// apply.
func IndexerSpec() *IndexerSpecApplyConfiguration {
	return &IndexerSpecApplyConfiguration{}
}

// WithDefinition sets the Definition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Definition field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithDefinition(value string) *IndexerSpecApplyConfiguration {
	b.Definition = &value
	return b
}

// WithDefinitionRef sets the DefinitionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefinitionRef field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithDefinitionRef(value string) *IndexerSpecApplyConfiguration {
	b.DefinitionRef = &value
	return b
}

// WithGeneric sets the Generic field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generic field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithGeneric(value *GenericNewznabApplyConfiguration) *IndexerSpecApplyConfiguration {
	b.Generic = value
	return b
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithBaseURL(value string) *IndexerSpecApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithEnabled(value bool) *IndexerSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithPriority(value int32) *IndexerSpecApplyConfiguration {
	b.Priority = &value
	return b
}

// WithSettings puts the entries into the Settings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Settings field,
// overwriting an existing map entries in Settings field with the same key.
func (b *IndexerSpecApplyConfiguration) WithSettings(entries map[string]string) *IndexerSpecApplyConfiguration {
	if b.Settings == nil && len(entries) > 0 {
		b.Settings = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Settings[k] = v
	}
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *IndexerSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithEnableRss sets the EnableRss field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableRss field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithEnableRss(value bool) *IndexerSpecApplyConfiguration {
	b.EnableRss = &value
	return b
}

// WithEnableAutomaticSearch sets the EnableAutomaticSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableAutomaticSearch field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithEnableAutomaticSearch(value bool) *IndexerSpecApplyConfiguration {
	b.EnableAutomaticSearch = &value
	return b
}

// WithEnableInteractiveSearch sets the EnableInteractiveSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableInteractiveSearch field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithEnableInteractiveSearch(value bool) *IndexerSpecApplyConfiguration {
	b.EnableInteractiveSearch = &value
	return b
}

// WithRssInterval sets the RssInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RssInterval field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithRssInterval(value metav1.Duration) *IndexerSpecApplyConfiguration {
	b.RssInterval = &value
	return b
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithLimits(value *LimitsApplyConfiguration) *IndexerSpecApplyConfiguration {
	b.Limits = value
	return b
}

// WithRequestDelay sets the RequestDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestDelay field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithRequestDelay(value metav1.Duration) *IndexerSpecApplyConfiguration {
	b.RequestDelay = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithTimeout(value metav1.Duration) *IndexerSpecApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithProxyRef sets the ProxyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProxyRef field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithProxyRef(value string) *IndexerSpecApplyConfiguration {
	b.ProxyRef = &value
	return b
}

// WithCategories adds the given value to the Categories field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Categories field.
func (b *IndexerSpecApplyConfiguration) WithCategories(values ...int32) *IndexerSpecApplyConfiguration {
	for i := range values {
		b.Categories = append(b.Categories, values[i])
	}
	return b
}

// WithAnimeCategories adds the given value to the AnimeCategories field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AnimeCategories field.
func (b *IndexerSpecApplyConfiguration) WithAnimeCategories(values ...int32) *IndexerSpecApplyConfiguration {
	for i := range values {
		b.AnimeCategories = append(b.AnimeCategories, values[i])
	}
	return b
}

// WithAnimeStandardFormatSearch sets the AnimeStandardFormatSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AnimeStandardFormatSearch field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithAnimeStandardFormatSearch(value bool) *IndexerSpecApplyConfiguration {
	b.AnimeStandardFormatSearch = &value
	return b
}

// WithMinimumSeeders sets the MinimumSeeders field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumSeeders field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithMinimumSeeders(value int32) *IndexerSpecApplyConfiguration {
	b.MinimumSeeders = &value
	return b
}

// WithSeedCriteria sets the SeedCriteria field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeedCriteria field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithSeedCriteria(value commonv1alpha1.SeedCriteria) *IndexerSpecApplyConfiguration {
	b.SeedCriteria = &value
	return b
}

// WithDownloadClientRef sets the DownloadClientRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownloadClientRef field is set to the value of the last call.
func (b *IndexerSpecApplyConfiguration) WithDownloadClientRef(value string) *IndexerSpecApplyConfiguration {
	b.DownloadClientRef = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *IndexerSpecApplyConfiguration) WithTags(values ...string) *IndexerSpecApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
