/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// EmbeddedSpecApplyConfiguration represents a declarative configuration of the EmbeddedSpec type for use
// with apply.
//
// EmbeddedSpec controls how subtitle tracks already inside the container are
// treated when deciding whether a language is satisfied.
type EmbeddedSpecApplyConfiguration struct {
	// Extract writes a matching embedded track out as a sidecar instead of
	// searching providers for it.
	Extract *bool `json:"extract,omitempty"`
	// IgnorePGS ignores image-based PGS tracks when matching embedded subtitles.
	IgnorePGS *bool `json:"ignorePGS,omitempty"`
	// IgnoreVobSub ignores image-based VobSub tracks when matching embedded subtitles.
	IgnoreVobSub *bool `json:"ignoreVobSub,omitempty"`
	// IgnoreASS ignores ASS/SSA tracks when matching embedded subtitles.
	IgnoreASS *bool `json:"ignoreASS,omitempty"`
	// SkipCommentary ignores tracks whose title marks them as commentary.
	SkipCommentary *bool `json:"skipCommentary,omitempty"`
}

// EmbeddedSpecApplyConfiguration constructs a declarative configuration of the EmbeddedSpec type for use with
// apply.
func EmbeddedSpec() *EmbeddedSpecApplyConfiguration {
	return &EmbeddedSpecApplyConfiguration{}
}

// WithExtract sets the Extract field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Extract field is set to the value of the last call.
func (b *EmbeddedSpecApplyConfiguration) WithExtract(value bool) *EmbeddedSpecApplyConfiguration {
	b.Extract = &value
	return b
}

// WithIgnorePGS sets the IgnorePGS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnorePGS field is set to the value of the last call.
func (b *EmbeddedSpecApplyConfiguration) WithIgnorePGS(value bool) *EmbeddedSpecApplyConfiguration {
	b.IgnorePGS = &value
	return b
}

// WithIgnoreVobSub sets the IgnoreVobSub field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreVobSub field is set to the value of the last call.
func (b *EmbeddedSpecApplyConfiguration) WithIgnoreVobSub(value bool) *EmbeddedSpecApplyConfiguration {
	b.IgnoreVobSub = &value
	return b
}

// WithIgnoreASS sets the IgnoreASS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreASS field is set to the value of the last call.
func (b *EmbeddedSpecApplyConfiguration) WithIgnoreASS(value bool) *EmbeddedSpecApplyConfiguration {
	b.IgnoreASS = &value
	return b
}

// WithSkipCommentary sets the SkipCommentary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipCommentary field is set to the value of the last call.
func (b *EmbeddedSpecApplyConfiguration) WithSkipCommentary(value bool) *EmbeddedSpecApplyConfiguration {
	b.SkipCommentary = &value
	return b
}
