/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	internal "github.com/mediactl/clustarr/api/applyconfiguration/subtitle/internal"
	subtitlev1alpha1 "github.com/mediactl/clustarr/api/subtitle/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SubtitleProfileApplyConfiguration represents a declarative configuration of the SubtitleProfile type for use
// with apply.
//
// SubtitleProfile describes the subtitle languages wanted for the MediaFiles
// it selects, and how candidates are scored, filtered and written.
type SubtitleProfileApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:""`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *SubtitleProfileSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *SubtitleProfileStatusApplyConfiguration `json:"status,omitempty"`
}

// SubtitleProfile constructs a declarative configuration of the SubtitleProfile type for use with
// apply.
func SubtitleProfile(name string) *SubtitleProfileApplyConfiguration {
	b := &SubtitleProfileApplyConfiguration{}
	b.WithName(name)
	b.WithKind("SubtitleProfile")
	b.WithAPIVersion("subtitle.clustarr.io/v1alpha1")
	return b
}

// ExtractSubtitleProfileFrom extracts the applied configuration owned by fieldManager from
// subtitleProfile for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// subtitleProfile must be a unmodified SubtitleProfile API object that was retrieved from the Kubernetes API.
// ExtractSubtitleProfileFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSubtitleProfileFrom(subtitleProfile *subtitlev1alpha1.SubtitleProfile, fieldManager string, subresource string) (*SubtitleProfileApplyConfiguration, error) {
	b := &SubtitleProfileApplyConfiguration{}
	err := managedfields.ExtractInto(subtitleProfile, internal.Parser().Type("com.github.mediactl.clustarr.api.subtitle.v1alpha1.SubtitleProfile"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(subtitleProfile.Name)

	b.WithKind("SubtitleProfile")
	b.WithAPIVersion("subtitle.clustarr.io/v1alpha1")
	return b, nil
}

// ExtractSubtitleProfile extracts the applied configuration owned by fieldManager from
// subtitleProfile. If no managedFields are found in subtitleProfile for fieldManager, a
// SubtitleProfileApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// subtitleProfile must be a unmodified SubtitleProfile API object that was retrieved from the Kubernetes API.
// ExtractSubtitleProfile provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSubtitleProfile(subtitleProfile *subtitlev1alpha1.SubtitleProfile, fieldManager string) (*SubtitleProfileApplyConfiguration, error) {
	return ExtractSubtitleProfileFrom(subtitleProfile, fieldManager, "")
}

// ExtractSubtitleProfileStatus extracts the applied configuration owned by fieldManager from
// subtitleProfile for the status subresource.
func ExtractSubtitleProfileStatus(subtitleProfile *subtitlev1alpha1.SubtitleProfile, fieldManager string) (*SubtitleProfileApplyConfiguration, error) {
	return ExtractSubtitleProfileFrom(subtitleProfile, fieldManager, "status")
}

func (b SubtitleProfileApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithKind(value string) *SubtitleProfileApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithAPIVersion(value string) *SubtitleProfileApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithName(value string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithGenerateName(value string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithNamespace(value string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithUID(value types.UID) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithResourceVersion(value string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithGeneration(value int64) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithCreationTimestamp(value metav1.Time) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SubtitleProfileApplyConfiguration) WithLabels(entries map[string]string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SubtitleProfileApplyConfiguration) WithAnnotations(entries map[string]string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *SubtitleProfileApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *SubtitleProfileApplyConfiguration) WithFinalizers(values ...string) *SubtitleProfileApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *SubtitleProfileApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithSpec(value *SubtitleProfileSpecApplyConfiguration) *SubtitleProfileApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *SubtitleProfileApplyConfiguration) WithStatus(value *SubtitleProfileStatusApplyConfiguration) *SubtitleProfileApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *SubtitleProfileApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *SubtitleProfileApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *SubtitleProfileApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *SubtitleProfileApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
