/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	subtitlev1alpha1 "github.com/mediactl/clustarr/api/subtitle/v1alpha1"
)

// SyncSpecApplyConfiguration represents a declarative configuration of the SyncSpec type for use
// with apply.
//
// SyncSpec configures subtitle re-timing. Deferred: it is parsed and validated
// in v1alpha1 but sync.enabled must be false.
type SyncSpecApplyConfiguration struct {
	// Enabled turns re-timing on. Must be false in v1alpha1.
	Enabled *bool `json:"enabled,omitempty"`
	// Tool is the re-timing tool to run.
	Tool *subtitlev1alpha1.SyncTool `json:"tool,omitempty"`
	// ThresholdPercent is the minimum subtitle score, per media kind, below
	// which a subtitle is not worth re-timing.
	ThresholdPercent *ScorePctApplyConfiguration `json:"thresholdPercent,omitempty"`
	// MaxOffsetSeconds is the largest shift, in seconds, that may be applied
	// before the result is rejected as a mismatch.
	MaxOffsetSeconds *int32 `json:"maxOffsetSeconds,omitempty"`
	// GSS uses golden-section search when aligning (ffsubsync). A pointer so a
	// Go client can send an explicit false; unset means true.
	GSS *bool `json:"gss,omitempty"`
	// NoFixFramerate disables framerate-ratio correction during alignment.
	// A pointer so a Go client can send an explicit false; unset means true.
	NoFixFramerate *bool `json:"noFixFramerate,omitempty"`
}

// SyncSpecApplyConfiguration constructs a declarative configuration of the SyncSpec type for use with
// apply.
func SyncSpec() *SyncSpecApplyConfiguration {
	return &SyncSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithEnabled(value bool) *SyncSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithTool sets the Tool field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tool field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithTool(value subtitlev1alpha1.SyncTool) *SyncSpecApplyConfiguration {
	b.Tool = &value
	return b
}

// WithThresholdPercent sets the ThresholdPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThresholdPercent field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithThresholdPercent(value *ScorePctApplyConfiguration) *SyncSpecApplyConfiguration {
	b.ThresholdPercent = value
	return b
}

// WithMaxOffsetSeconds sets the MaxOffsetSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxOffsetSeconds field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithMaxOffsetSeconds(value int32) *SyncSpecApplyConfiguration {
	b.MaxOffsetSeconds = &value
	return b
}

// WithGSS sets the GSS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GSS field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithGSS(value bool) *SyncSpecApplyConfiguration {
	b.GSS = &value
	return b
}

// WithNoFixFramerate sets the NoFixFramerate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NoFixFramerate field is set to the value of the last call.
func (b *SyncSpecApplyConfiguration) WithNoFixFramerate(value bool) *SyncSpecApplyConfiguration {
	b.NoFixFramerate = &value
	return b
}
