/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AlbumMetadataApplyConfiguration represents a declarative configuration of the AlbumMetadata type for use
// with apply.
//
// AlbumMetadata is the provider metadata cached on the album.
type AlbumMetadataApplyConfiguration struct {
	// Title is the album title.
	Title *string `json:"title,omitempty"`
	// Disambiguation distinguishes same-named release groups.
	Disambiguation *string `json:"disambiguation,omitempty"`
	// Overview is the album description.
	Overview *string `json:"overview,omitempty"`
	// AlbumType is the MusicBrainz primary release-group type.
	AlbumType *string `json:"albumType,omitempty"`
	// SecondaryTypes are the MusicBrainz secondary release-group types.
	SecondaryTypes []string `json:"secondaryTypes,omitempty"`
	// ReleaseDate is the earliest release date of the release group.
	ReleaseDate *v1.Time `json:"releaseDate,omitempty"`
	// Releases lists the releases in the release group.
	Releases []ReleaseSummaryApplyConfiguration `json:"releases,omitempty"`
	// SelectedReleaseID is the release the tracks were taken from.
	SelectedReleaseID *string `json:"selectedReleaseID,omitempty"`
	// Images lists the cover art published by the provider.
	Images []ImageApplyConfiguration `json:"images,omitempty"`
	// RefreshedAt is when the metadata was last fetched.
	RefreshedAt *v1.Time `json:"refreshedAt,omitempty"`
}

// AlbumMetadataApplyConfiguration constructs a declarative configuration of the AlbumMetadata type for use with
// apply.
func AlbumMetadata() *AlbumMetadataApplyConfiguration {
	return &AlbumMetadataApplyConfiguration{}
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithTitle(value string) *AlbumMetadataApplyConfiguration {
	b.Title = &value
	return b
}

// WithDisambiguation sets the Disambiguation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disambiguation field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithDisambiguation(value string) *AlbumMetadataApplyConfiguration {
	b.Disambiguation = &value
	return b
}

// WithOverview sets the Overview field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Overview field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithOverview(value string) *AlbumMetadataApplyConfiguration {
	b.Overview = &value
	return b
}

// WithAlbumType sets the AlbumType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlbumType field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithAlbumType(value string) *AlbumMetadataApplyConfiguration {
	b.AlbumType = &value
	return b
}

// WithSecondaryTypes adds the given value to the SecondaryTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecondaryTypes field.
func (b *AlbumMetadataApplyConfiguration) WithSecondaryTypes(values ...string) *AlbumMetadataApplyConfiguration {
	for i := range values {
		b.SecondaryTypes = append(b.SecondaryTypes, values[i])
	}
	return b
}

// WithReleaseDate sets the ReleaseDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseDate field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithReleaseDate(value v1.Time) *AlbumMetadataApplyConfiguration {
	b.ReleaseDate = &value
	return b
}

// WithReleases adds the given value to the Releases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Releases field.
func (b *AlbumMetadataApplyConfiguration) WithReleases(values ...*ReleaseSummaryApplyConfiguration) *AlbumMetadataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReleases")
		}
		b.Releases = append(b.Releases, *values[i])
	}
	return b
}

// WithSelectedReleaseID sets the SelectedReleaseID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectedReleaseID field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithSelectedReleaseID(value string) *AlbumMetadataApplyConfiguration {
	b.SelectedReleaseID = &value
	return b
}

// WithImages adds the given value to the Images field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Images field.
func (b *AlbumMetadataApplyConfiguration) WithImages(values ...*ImageApplyConfiguration) *AlbumMetadataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImages")
		}
		b.Images = append(b.Images, *values[i])
	}
	return b
}

// WithRefreshedAt sets the RefreshedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RefreshedAt field is set to the value of the last call.
func (b *AlbumMetadataApplyConfiguration) WithRefreshedAt(value v1.Time) *AlbumMetadataApplyConfiguration {
	b.RefreshedAt = &value
	return b
}
