/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
	commonv1alpha1 "github.com/mediactl/clustarr/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AlbumStatusApplyConfiguration represents a declarative configuration of the AlbumStatus type for use
// with apply.
//
// AlbumStatus describes the observed state of Album.
type AlbumStatusApplyConfiguration struct {
	// ObservedGeneration is the generation of the spec this status reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the album's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Metadata is the cached provider metadata.
	Metadata *AlbumMetadataApplyConfiguration `json:"metadata,omitempty"`
	// Tracks is the track listing of the selected release. Releases with more
	// than 200 tracks raise the Invalid condition instead of being truncated
	// silently.
	Tracks []TrackApplyConfiguration `json:"tracks,omitempty"`
	// Phase is the coarse lifecycle state of the album.
	Phase *catalogv1alpha1.AlbumPhase `json:"phase,omitempty"`
	// Path is the resolved folder on disk.
	Path *string `json:"path,omitempty"`
	// TrackFileCount is the number of tracks with an imported file.
	TrackFileCount *int32 `json:"trackFileCount,omitempty"`
	// Quality is the lowest quality across the album's imported tracks.
	Quality *commonv1alpha1.Quality `json:"quality,omitempty"`
	// FormatScore is the custom-format score of the imported release.
	FormatScore *int32 `json:"formatScore,omitempty"`
	// CutoffMet is true when the imported tracks meet the profile cutoff.
	CutoffMet *bool `json:"cutoffMet,omitempty"`
	// ActiveDownloadRef is the Download currently working on this album.
	ActiveDownloadRef *string `json:"activeDownloadRef,omitempty"`
	// PendingGrab is a chosen release waiting out a DelayProfile delay.
	PendingGrab *PendingGrabApplyConfiguration `json:"pendingGrab,omitempty"`
	// LastSearchedAt is when the album was last searched for.
	LastSearchedAt *metav1.Time `json:"lastSearchedAt,omitempty"`
	// SearchAttempts counts the searches made for this album.
	SearchAttempts *commonv1alpha1.Attempts `json:"searchAttempts,omitempty"`
}

// AlbumStatusApplyConfiguration constructs a declarative configuration of the AlbumStatus type for use with
// apply.
func AlbumStatus() *AlbumStatusApplyConfiguration {
	return &AlbumStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithObservedGeneration(value int64) *AlbumStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AlbumStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *AlbumStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithMetadata(value *AlbumMetadataApplyConfiguration) *AlbumStatusApplyConfiguration {
	b.Metadata = value
	return b
}

// WithTracks adds the given value to the Tracks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tracks field.
func (b *AlbumStatusApplyConfiguration) WithTracks(values ...*TrackApplyConfiguration) *AlbumStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTracks")
		}
		b.Tracks = append(b.Tracks, *values[i])
	}
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithPhase(value catalogv1alpha1.AlbumPhase) *AlbumStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithPath(value string) *AlbumStatusApplyConfiguration {
	b.Path = &value
	return b
}

// WithTrackFileCount sets the TrackFileCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrackFileCount field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithTrackFileCount(value int32) *AlbumStatusApplyConfiguration {
	b.TrackFileCount = &value
	return b
}

// WithQuality sets the Quality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quality field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithQuality(value commonv1alpha1.Quality) *AlbumStatusApplyConfiguration {
	b.Quality = &value
	return b
}

// WithFormatScore sets the FormatScore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FormatScore field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithFormatScore(value int32) *AlbumStatusApplyConfiguration {
	b.FormatScore = &value
	return b
}

// WithCutoffMet sets the CutoffMet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CutoffMet field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithCutoffMet(value bool) *AlbumStatusApplyConfiguration {
	b.CutoffMet = &value
	return b
}

// WithActiveDownloadRef sets the ActiveDownloadRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveDownloadRef field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithActiveDownloadRef(value string) *AlbumStatusApplyConfiguration {
	b.ActiveDownloadRef = &value
	return b
}

// WithPendingGrab sets the PendingGrab field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PendingGrab field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithPendingGrab(value *PendingGrabApplyConfiguration) *AlbumStatusApplyConfiguration {
	b.PendingGrab = value
	return b
}

// WithLastSearchedAt sets the LastSearchedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSearchedAt field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithLastSearchedAt(value metav1.Time) *AlbumStatusApplyConfiguration {
	b.LastSearchedAt = &value
	return b
}

// WithSearchAttempts sets the SearchAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchAttempts field is set to the value of the last call.
func (b *AlbumStatusApplyConfiguration) WithSearchAttempts(value commonv1alpha1.Attempts) *AlbumStatusApplyConfiguration {
	b.SearchAttempts = &value
	return b
}
