/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
)

// ArrListApplyConfiguration represents a declarative configuration of the ArrList type for use
// with apply.
//
// ArrList follows the library of another *arr instance, including another
// Clustarr.
type ArrListApplyConfiguration struct {
	// BaseURL is the instance's base URL.
	BaseURL *string `json:"baseURL,omitempty"`
	// Kind is the *arr flavour being followed.
	Kind *catalogv1alpha1.ArrKind `json:"kind,omitempty"`
}

// ArrListApplyConfiguration constructs a declarative configuration of the ArrList type for use with
// apply.
func ArrList() *ArrListApplyConfiguration {
	return &ArrListApplyConfiguration{}
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *ArrListApplyConfiguration) WithBaseURL(value string) *ArrListApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ArrListApplyConfiguration) WithKind(value catalogv1alpha1.ArrKind) *ArrListApplyConfiguration {
	b.Kind = &value
	return b
}
