/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
)

// ArtistAddOptionsApplyConfiguration represents a declarative configuration of the ArtistAddOptions type for use
// with apply.
//
// ArtistAddOptions are applied exactly once, when the artist is first reconciled.
type ArtistAddOptionsApplyConfiguration struct {
	// Monitor selects which albums start out monitored.
	Monitor *catalogv1alpha1.ArtistMonitorMode `json:"monitor,omitempty"`
	// SearchForMissing searches for missing albums on add.
	SearchForMissing *bool `json:"searchForMissing,omitempty"`
}

// ArtistAddOptionsApplyConfiguration constructs a declarative configuration of the ArtistAddOptions type for use with
// apply.
func ArtistAddOptions() *ArtistAddOptionsApplyConfiguration {
	return &ArtistAddOptionsApplyConfiguration{}
}

// WithMonitor sets the Monitor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitor field is set to the value of the last call.
func (b *ArtistAddOptionsApplyConfiguration) WithMonitor(value catalogv1alpha1.ArtistMonitorMode) *ArtistAddOptionsApplyConfiguration {
	b.Monitor = &value
	return b
}

// WithSearchForMissing sets the SearchForMissing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchForMissing field is set to the value of the last call.
func (b *ArtistAddOptionsApplyConfiguration) WithSearchForMissing(value bool) *ArtistAddOptionsApplyConfiguration {
	b.SearchForMissing = &value
	return b
}
