/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtistMetadataApplyConfiguration represents a declarative configuration of the ArtistMetadata type for use
// with apply.
//
// ArtistMetadata is the provider metadata cached on the artist.
type ArtistMetadataApplyConfiguration struct {
	// Name is the artist name.
	Name *string `json:"name,omitempty"`
	// SortName is the name used for sorting.
	SortName *string `json:"sortName,omitempty"`
	// Disambiguation distinguishes same-named artists.
	Disambiguation *string `json:"disambiguation,omitempty"`
	// Type is the MusicBrainz artist type, e.g. Person or Group.
	Type *string `json:"type,omitempty"`
	// Overview is the artist biography.
	Overview *string `json:"overview,omitempty"`
	// Status is the upstream activity status.
	Status *catalogv1alpha1.ArtistRunStatus `json:"status,omitempty"`
	// Genres lists the genres.
	Genres []string `json:"genres,omitempty"`
	// ExternalIDs maps provider names (musicbrainz, fanart, ...) to their IDs.
	ExternalIDs map[string]string `json:"externalIDs,omitempty"`
	// Images lists the artwork published by the provider.
	Images []ImageApplyConfiguration `json:"images,omitempty"`
	// RefreshedAt is when the metadata was last fetched.
	RefreshedAt *v1.Time `json:"refreshedAt,omitempty"`
}

// ArtistMetadataApplyConfiguration constructs a declarative configuration of the ArtistMetadata type for use with
// apply.
func ArtistMetadata() *ArtistMetadataApplyConfiguration {
	return &ArtistMetadataApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithName(value string) *ArtistMetadataApplyConfiguration {
	b.Name = &value
	return b
}

// WithSortName sets the SortName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SortName field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithSortName(value string) *ArtistMetadataApplyConfiguration {
	b.SortName = &value
	return b
}

// WithDisambiguation sets the Disambiguation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disambiguation field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithDisambiguation(value string) *ArtistMetadataApplyConfiguration {
	b.Disambiguation = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithType(value string) *ArtistMetadataApplyConfiguration {
	b.Type = &value
	return b
}

// WithOverview sets the Overview field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Overview field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithOverview(value string) *ArtistMetadataApplyConfiguration {
	b.Overview = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithStatus(value catalogv1alpha1.ArtistRunStatus) *ArtistMetadataApplyConfiguration {
	b.Status = &value
	return b
}

// WithGenres adds the given value to the Genres field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Genres field.
func (b *ArtistMetadataApplyConfiguration) WithGenres(values ...string) *ArtistMetadataApplyConfiguration {
	for i := range values {
		b.Genres = append(b.Genres, values[i])
	}
	return b
}

// WithExternalIDs puts the entries into the ExternalIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExternalIDs field,
// overwriting an existing map entries in ExternalIDs field with the same key.
func (b *ArtistMetadataApplyConfiguration) WithExternalIDs(entries map[string]string) *ArtistMetadataApplyConfiguration {
	if b.ExternalIDs == nil && len(entries) > 0 {
		b.ExternalIDs = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExternalIDs[k] = v
	}
	return b
}

// WithImages adds the given value to the Images field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Images field.
func (b *ArtistMetadataApplyConfiguration) WithImages(values ...*ImageApplyConfiguration) *ArtistMetadataApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImages")
		}
		b.Images = append(b.Images, *values[i])
	}
	return b
}

// WithRefreshedAt sets the RefreshedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RefreshedAt field is set to the value of the last call.
func (b *ArtistMetadataApplyConfiguration) WithRefreshedAt(value v1.Time) *ArtistMetadataApplyConfiguration {
	b.RefreshedAt = &value
	return b
}
