/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ChapterApplyConfiguration represents a declarative configuration of the Chapter type for use
// with apply.
//
// Chapter is one chapter marker of an audiobook.
type ChapterApplyConfiguration struct {
	// Title is the chapter title.
	Title *string `json:"title,omitempty"`
	// StartMs is the chapter start offset in milliseconds.
	StartMs *int64 `json:"startMs,omitempty"`
}

// ChapterApplyConfiguration constructs a declarative configuration of the Chapter type for use with
// apply.
func Chapter() *ChapterApplyConfiguration {
	return &ChapterApplyConfiguration{}
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *ChapterApplyConfiguration) WithTitle(value string) *ChapterApplyConfiguration {
	b.Title = &value
	return b
}

// WithStartMs sets the StartMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartMs field is set to the value of the last call.
func (b *ChapterApplyConfiguration) WithStartMs(value int64) *ChapterApplyConfiguration {
	b.StartMs = &value
	return b
}
