/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComicStatusApplyConfiguration represents a declarative configuration of the ComicStatus type for use
// with apply.
//
// ComicStatus describes the observed state of Comic.
type ComicStatusApplyConfiguration struct {
	// ObservedGeneration is the generation of the spec this status reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the comic's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Metadata is the cached provider metadata.
	Metadata *ComicMetadataApplyConfiguration `json:"metadata,omitempty"`
	// Path is the resolved folder on disk.
	Path *string `json:"path,omitempty"`
	// IssueFileCount is the number of issues with an imported file.
	IssueFileCount *int32 `json:"issueFileCount,omitempty"`
	// NextPullDate is when the next issue is expected on the pull list.
	NextPullDate *metav1.Time `json:"nextPullDate,omitempty"`
}

// ComicStatusApplyConfiguration constructs a declarative configuration of the ComicStatus type for use with
// apply.
func ComicStatus() *ComicStatusApplyConfiguration {
	return &ComicStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ComicStatusApplyConfiguration) WithObservedGeneration(value int64) *ComicStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComicStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComicStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ComicStatusApplyConfiguration) WithMetadata(value *ComicMetadataApplyConfiguration) *ComicStatusApplyConfiguration {
	b.Metadata = value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ComicStatusApplyConfiguration) WithPath(value string) *ComicStatusApplyConfiguration {
	b.Path = &value
	return b
}

// WithIssueFileCount sets the IssueFileCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssueFileCount field is set to the value of the last call.
func (b *ComicStatusApplyConfiguration) WithIssueFileCount(value int32) *ComicStatusApplyConfiguration {
	b.IssueFileCount = &value
	return b
}

// WithNextPullDate sets the NextPullDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextPullDate field is set to the value of the last call.
func (b *ComicStatusApplyConfiguration) WithNextPullDate(value metav1.Time) *ComicStatusApplyConfiguration {
	b.NextPullDate = &value
	return b
}
