/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
	commonv1alpha1 "github.com/mediactl/clustarr/api/common/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DownloadImportSummaryApplyConfiguration represents a declarative configuration of the DownloadImportSummary type for use
// with apply.
//
// DownloadImportSummary is the grab's import, summarised from its
// clustarr-imports record (ADR-0019 §6.9); the per-file detail stays in the
// record.
type DownloadImportSummaryApplyConfiguration struct {
	Phase         *catalogv1alpha1.ImportPhase         `json:"phase,omitempty"`
	Class         *commonv1alpha1.ImportRejectionClass `json:"class,omitempty"`
	Message       *string                              `json:"message,omitempty"`
	Attempts      *int32                               `json:"attempts,omitempty"`
	NextAttemptAt *v1.Time                             `json:"nextAttemptAt,omitempty"`
	HeldSince     *v1.Time                             `json:"heldSince,omitempty"`
	ImportedAt    *v1.Time                             `json:"importedAt,omitempty"`
	// Files is how many files the approved plan places; the entry reads
	// Imported only when that many MediaFiles name this entry's ID in
	// spec.importedFrom.downloadRef.
	Files *int32 `json:"files,omitempty"`
	// Dispatch fences the inspect and execute tasks (§6.9).
	Dispatch *DispatchApplyConfiguration `json:"dispatch,omitempty"`
}

// DownloadImportSummaryApplyConfiguration constructs a declarative configuration of the DownloadImportSummary type for use with
// apply.
func DownloadImportSummary() *DownloadImportSummaryApplyConfiguration {
	return &DownloadImportSummaryApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithPhase(value catalogv1alpha1.ImportPhase) *DownloadImportSummaryApplyConfiguration {
	b.Phase = &value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithClass(value commonv1alpha1.ImportRejectionClass) *DownloadImportSummaryApplyConfiguration {
	b.Class = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithMessage(value string) *DownloadImportSummaryApplyConfiguration {
	b.Message = &value
	return b
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithAttempts(value int32) *DownloadImportSummaryApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithNextAttemptAt sets the NextAttemptAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextAttemptAt field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithNextAttemptAt(value v1.Time) *DownloadImportSummaryApplyConfiguration {
	b.NextAttemptAt = &value
	return b
}

// WithHeldSince sets the HeldSince field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeldSince field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithHeldSince(value v1.Time) *DownloadImportSummaryApplyConfiguration {
	b.HeldSince = &value
	return b
}

// WithImportedAt sets the ImportedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImportedAt field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithImportedAt(value v1.Time) *DownloadImportSummaryApplyConfiguration {
	b.ImportedAt = &value
	return b
}

// WithFiles sets the Files field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Files field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithFiles(value int32) *DownloadImportSummaryApplyConfiguration {
	b.Files = &value
	return b
}

// WithDispatch sets the Dispatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dispatch field is set to the value of the last call.
func (b *DownloadImportSummaryApplyConfiguration) WithDispatch(value *DispatchApplyConfiguration) *DownloadImportSummaryApplyConfiguration {
	b.Dispatch = value
	return b
}
