/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ImportExclusionStatusApplyConfiguration represents a declarative configuration of the ImportExclusionStatus type for use
// with apply.
//
// ImportExclusionStatus describes the observed state of ImportExclusion.
type ImportExclusionStatusApplyConfiguration struct {
	// ObservedGeneration is the generation of the spec this status reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the exclusion's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// MatchCount is how many list entries this exclusion has suppressed.
	MatchCount *int32 `json:"matchCount,omitempty"`
	// LastMatchedAt is when the exclusion last suppressed a list entry.
	LastMatchedAt *metav1.Time `json:"lastMatchedAt,omitempty"`
}

// ImportExclusionStatusApplyConfiguration constructs a declarative configuration of the ImportExclusionStatus type for use with
// apply.
func ImportExclusionStatus() *ImportExclusionStatusApplyConfiguration {
	return &ImportExclusionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ImportExclusionStatusApplyConfiguration) WithObservedGeneration(value int64) *ImportExclusionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ImportExclusionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ImportExclusionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMatchCount sets the MatchCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchCount field is set to the value of the last call.
func (b *ImportExclusionStatusApplyConfiguration) WithMatchCount(value int32) *ImportExclusionStatusApplyConfiguration {
	b.MatchCount = &value
	return b
}

// WithLastMatchedAt sets the LastMatchedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastMatchedAt field is set to the value of the last call.
func (b *ImportExclusionStatusApplyConfiguration) WithLastMatchedAt(value metav1.Time) *ImportExclusionStatusApplyConfiguration {
	b.LastMatchedAt = &value
	return b
}
