/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LegacyDownloadsApplyConfiguration represents a declarative configuration of the LegacyDownloads type for use
// with apply.
//
// LegacyDownloads is release N's record of the Downloads this owner
// adopted (ADR-0019 §10.2). Release N+1 removes it.
type LegacyDownloadsApplyConfiguration struct {
	Adopted []LegacyDownloadApplyConfiguration `json:"adopted,omitempty"`
	// Held is "TooMany" while the owner has more live Downloads than its
	// entry cap; nothing is truncated.
	Held    *string `json:"held,omitempty"`
	Message *string `json:"message,omitempty"`
}

// LegacyDownloadsApplyConfiguration constructs a declarative configuration of the LegacyDownloads type for use with
// apply.
func LegacyDownloads() *LegacyDownloadsApplyConfiguration {
	return &LegacyDownloadsApplyConfiguration{}
}

// WithAdopted adds the given value to the Adopted field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Adopted field.
func (b *LegacyDownloadsApplyConfiguration) WithAdopted(values ...*LegacyDownloadApplyConfiguration) *LegacyDownloadsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAdopted")
		}
		b.Adopted = append(b.Adopted, *values[i])
	}
	return b
}

// WithHeld sets the Held field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Held field is set to the value of the last call.
func (b *LegacyDownloadsApplyConfiguration) WithHeld(value string) *LegacyDownloadsApplyConfiguration {
	b.Held = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *LegacyDownloadsApplyConfiguration) WithMessage(value string) *LegacyDownloadsApplyConfiguration {
	b.Message = &value
	return b
}
