/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LegacyDownloadApplyConfiguration represents a declarative configuration of the LegacyDownload type for use
// with apply.
//
// LegacyDownload is one Download release N adopted, blocklisted, dismissed
// or is removing for this owner.
type LegacyDownloadApplyConfiguration struct {
	Name    *string                        `json:"name,omitempty"`
	UID     *string                        `json:"uid,omitempty"`
	Outcome *catalogv1alpha1.LegacyOutcome `json:"outcome,omitempty"`
	At      *v1.Time                       `json:"at,omitempty"`
}

// LegacyDownloadApplyConfiguration constructs a declarative configuration of the LegacyDownload type for use with
// apply.
func LegacyDownload() *LegacyDownloadApplyConfiguration {
	return &LegacyDownloadApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LegacyDownloadApplyConfiguration) WithName(value string) *LegacyDownloadApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *LegacyDownloadApplyConfiguration) WithUID(value string) *LegacyDownloadApplyConfiguration {
	b.UID = &value
	return b
}

// WithOutcome sets the Outcome field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Outcome field is set to the value of the last call.
func (b *LegacyDownloadApplyConfiguration) WithOutcome(value catalogv1alpha1.LegacyOutcome) *LegacyDownloadApplyConfiguration {
	b.Outcome = &value
	return b
}

// WithAt sets the At field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the At field is set to the value of the last call.
func (b *LegacyDownloadApplyConfiguration) WithAt(value v1.Time) *LegacyDownloadApplyConfiguration {
	b.At = &value
	return b
}
