/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/mediactl/clustarr/api/common/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MediaFileStatusApplyConfiguration represents a declarative configuration of the MediaFileStatus type for use
// with apply.
//
// MediaFileStatus describes the observed state of MediaFile.
type MediaFileStatusApplyConfiguration struct {
	// ObservedGeneration is the generation of the spec this status reflects.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the file's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ProbeHash is sha1(path|size|mtime); a change makes downstream services replan.
	ProbeHash *string `json:"probeHash,omitempty"`
	// ProbedAt is when the file was last probed.
	ProbedAt *metav1.Time `json:"probedAt,omitempty"`
	// ProbeVersion is the version of the probe that last described the
	// file (pkg/mediainfo.ProbeVersion). A file probed by an older version
	// is probed again, with probeHash unchanged: the hash is the file's
	// identity to captionarr and squasharr, and its bytes did not change.
	// Zero is a file probed before versions existed.
	ProbeVersion *int32 `json:"probeVersion,omitempty"`
	// MediaInfo is the technical description produced by the probe. Its
	// transcodeProfile is the file's CLUSTARR_PROFILE tag: with it, or with
	// spec.original false, the file is transcoded and final
	// (app/catalog/controller/rollup.Transcoded) -- the tag is what recognises
	// a file an earlier install transcoded, found by a rescan.
	MediaInfo *commonv1alpha1.MediaInfo `json:"mediaInfo,omitempty"`
	// Sidecars lists the subtitle and metadata files found next to this one.
	Sidecars []SidecarApplyConfiguration `json:"sidecars,omitempty"`
	// Transcode is transcodarr's view of this file.
	Transcode *TranscodeStateApplyConfiguration `json:"transcode,omitempty"`
	// GraftTag is the CLUSTARR_GRAFT tag of the last audio graft catalogarr
	// incorporated into this file (anime dual-audio spec §7.2), and
	// GraftedAt when. A graft is not a transcode: spec.original stays as it
	// was, but from the first graft catalogarr owns spec.path, sizeBytes and
	// modTime, as after a transcode swap.
	GraftTag  *string      `json:"graftTag,omitempty"`
	GraftedAt *metav1.Time `json:"graftedAt,omitempty"`
	// Naming is the file's canonical path under its RootFolder's naming
	// preset, rendered by catalogarr from the item's metadata, the
	// release-time spec and the probe; importarr performs the rename.
	Naming *NamingStatusApplyConfiguration `json:"naming,omitempty"`
	// Markers are the skip segments TheIntroDB publishes for this file,
	// fetched by catalogarr's marker worker (field manager
	// catalogarr-markers) with the probe's duration, and seeded into Plex
	// by cluster-plex (spec 2026-09-30 plex-analyze-bypass).
	Markers *FileMarkersApplyConfiguration `json:"markers,omitempty"`
}

// MediaFileStatusApplyConfiguration constructs a declarative configuration of the MediaFileStatus type for use with
// apply.
func MediaFileStatus() *MediaFileStatusApplyConfiguration {
	return &MediaFileStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithObservedGeneration(value int64) *MediaFileStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MediaFileStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MediaFileStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithProbeHash sets the ProbeHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProbeHash field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithProbeHash(value string) *MediaFileStatusApplyConfiguration {
	b.ProbeHash = &value
	return b
}

// WithProbedAt sets the ProbedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProbedAt field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithProbedAt(value metav1.Time) *MediaFileStatusApplyConfiguration {
	b.ProbedAt = &value
	return b
}

// WithProbeVersion sets the ProbeVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProbeVersion field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithProbeVersion(value int32) *MediaFileStatusApplyConfiguration {
	b.ProbeVersion = &value
	return b
}

// WithMediaInfo sets the MediaInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MediaInfo field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithMediaInfo(value commonv1alpha1.MediaInfo) *MediaFileStatusApplyConfiguration {
	b.MediaInfo = &value
	return b
}

// WithSidecars adds the given value to the Sidecars field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sidecars field.
func (b *MediaFileStatusApplyConfiguration) WithSidecars(values ...*SidecarApplyConfiguration) *MediaFileStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSidecars")
		}
		b.Sidecars = append(b.Sidecars, *values[i])
	}
	return b
}

// WithTranscode sets the Transcode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transcode field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithTranscode(value *TranscodeStateApplyConfiguration) *MediaFileStatusApplyConfiguration {
	b.Transcode = value
	return b
}

// WithGraftTag sets the GraftTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GraftTag field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithGraftTag(value string) *MediaFileStatusApplyConfiguration {
	b.GraftTag = &value
	return b
}

// WithGraftedAt sets the GraftedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GraftedAt field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithGraftedAt(value metav1.Time) *MediaFileStatusApplyConfiguration {
	b.GraftedAt = &value
	return b
}

// WithNaming sets the Naming field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Naming field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithNaming(value *NamingStatusApplyConfiguration) *MediaFileStatusApplyConfiguration {
	b.Naming = value
	return b
}

// WithMarkers sets the Markers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Markers field is set to the value of the last call.
func (b *MediaFileStatusApplyConfiguration) WithMarkers(value *FileMarkersApplyConfiguration) *MediaFileStatusApplyConfiguration {
	b.Markers = value
	return b
}
