/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
)

// RootDefaultsApplyConfiguration represents a declarative configuration of the RootDefaults type for use
// with apply.
//
// RootDefaults are the per-folder defaults applied to items added under this
// root folder when the item itself does not set them.
type RootDefaultsApplyConfiguration struct {
	// QualityProfileRef is the default QualityProfile name.
	QualityProfileRef *string `json:"qualityProfileRef,omitempty"`
	// TranscodeProfileRef is the default TranscodeProfile name.
	TranscodeProfileRef *string `json:"transcodeProfileRef,omitempty"`
	// SubtitleProfileRef is the default SubtitleProfile name.
	SubtitleProfileRef *string `json:"subtitleProfileRef,omitempty"`
	// DelayProfileRef is the default DelayProfile name.
	DelayProfileRef *string `json:"delayProfileRef,omitempty"`
	// Monitored is the default monitored flag for new items.
	Monitored *bool `json:"monitored,omitempty"`
	// MonitorNewItems is the default handling of newly discovered children.
	MonitorNewItems *catalogv1alpha1.MonitorNewItemsMode `json:"monitorNewItems,omitempty"`
	// SearchOnAdd triggers a search as soon as an item is added.
	SearchOnAdd *bool `json:"searchOnAdd,omitempty"`
	// MinimumAvailability is the default minimum availability for movies.
	MinimumAvailability *catalogv1alpha1.MinimumAvailability `json:"minimumAvailability,omitempty"`
	// SeriesType is the default series type for series added here.
	SeriesType *catalogv1alpha1.SeriesType `json:"seriesType,omitempty"`
	// SeasonFolder is the default season-folder flag for series added here.
	SeasonFolder *bool `json:"seasonFolder,omitempty"`
	// Tags are applied to every item added under this root folder.
	Tags []string `json:"tags,omitempty"`
}

// RootDefaultsApplyConfiguration constructs a declarative configuration of the RootDefaults type for use with
// apply.
func RootDefaults() *RootDefaultsApplyConfiguration {
	return &RootDefaultsApplyConfiguration{}
}

// WithQualityProfileRef sets the QualityProfileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QualityProfileRef field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithQualityProfileRef(value string) *RootDefaultsApplyConfiguration {
	b.QualityProfileRef = &value
	return b
}

// WithTranscodeProfileRef sets the TranscodeProfileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TranscodeProfileRef field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithTranscodeProfileRef(value string) *RootDefaultsApplyConfiguration {
	b.TranscodeProfileRef = &value
	return b
}

// WithSubtitleProfileRef sets the SubtitleProfileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubtitleProfileRef field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithSubtitleProfileRef(value string) *RootDefaultsApplyConfiguration {
	b.SubtitleProfileRef = &value
	return b
}

// WithDelayProfileRef sets the DelayProfileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DelayProfileRef field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithDelayProfileRef(value string) *RootDefaultsApplyConfiguration {
	b.DelayProfileRef = &value
	return b
}

// WithMonitored sets the Monitored field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitored field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithMonitored(value bool) *RootDefaultsApplyConfiguration {
	b.Monitored = &value
	return b
}

// WithMonitorNewItems sets the MonitorNewItems field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MonitorNewItems field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithMonitorNewItems(value catalogv1alpha1.MonitorNewItemsMode) *RootDefaultsApplyConfiguration {
	b.MonitorNewItems = &value
	return b
}

// WithSearchOnAdd sets the SearchOnAdd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SearchOnAdd field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithSearchOnAdd(value bool) *RootDefaultsApplyConfiguration {
	b.SearchOnAdd = &value
	return b
}

// WithMinimumAvailability sets the MinimumAvailability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumAvailability field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithMinimumAvailability(value catalogv1alpha1.MinimumAvailability) *RootDefaultsApplyConfiguration {
	b.MinimumAvailability = &value
	return b
}

// WithSeriesType sets the SeriesType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeriesType field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithSeriesType(value catalogv1alpha1.SeriesType) *RootDefaultsApplyConfiguration {
	b.SeriesType = &value
	return b
}

// WithSeasonFolder sets the SeasonFolder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeasonFolder field is set to the value of the last call.
func (b *RootDefaultsApplyConfiguration) WithSeasonFolder(value bool) *RootDefaultsApplyConfiguration {
	b.SeasonFolder = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *RootDefaultsApplyConfiguration) WithTags(values ...string) *RootDefaultsApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
