/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SeasonTypeRefApplyConfiguration represents a declarative configuration of the SeasonTypeRef type for use
// with apply.
//
// SeasonTypeRef names one of a series' episode orderings as the provider
// calls it (TVDB seasonTypes: "official" is "Aired Order").
type SeasonTypeRefApplyConfiguration struct {
	// ID is the ordering's identifier, e.g. "official", "dvd", "absolute".
	ID *string `json:"id,omitempty"`
	// Name is the ordering's human-readable name.
	Name *string `json:"name,omitempty"`
}

// SeasonTypeRefApplyConfiguration constructs a declarative configuration of the SeasonTypeRef type for use with
// apply.
func SeasonTypeRef() *SeasonTypeRefApplyConfiguration {
	return &SeasonTypeRefApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *SeasonTypeRefApplyConfiguration) WithID(value string) *SeasonTypeRefApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SeasonTypeRefApplyConfiguration) WithName(value string) *SeasonTypeRefApplyConfiguration {
	b.Name = &value
	return b
}
