/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "github.com/mediactl/clustarr/api/catalog/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SegmentAnalysisApplyConfiguration represents a declarative configuration of the SegmentAnalysis type for use
// with apply.
//
// SegmentAnalysis records clustarr's own analysis of a file
// (segmentarr-worker), beside TheIntroDB's fetch bookkeeping.
type SegmentAnalysisApplyConfiguration struct {
	// Result is Found, NotFound or Error.
	Result *catalogv1alpha1.MarkersResult `json:"result,omitempty"`
	// AnalyzedAt is when the worker's result was recorded.
	AnalyzedAt *v1.Time `json:"analyzedAt,omitempty"`
	// ForProbeHash is status.probeHash of the file analyzed.
	ForProbeHash *string `json:"forProbeHash,omitempty"`
	// Version is pkg/segments.AnalyzerVersion when analyzed; an older one
	// is analyzed again.
	Version *int32 `json:"version,omitempty"`
	// Message says why the analysis ended NotFound or Error.
	Message *string `json:"message,omitempty"`
}

// SegmentAnalysisApplyConfiguration constructs a declarative configuration of the SegmentAnalysis type for use with
// apply.
func SegmentAnalysis() *SegmentAnalysisApplyConfiguration {
	return &SegmentAnalysisApplyConfiguration{}
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *SegmentAnalysisApplyConfiguration) WithResult(value catalogv1alpha1.MarkersResult) *SegmentAnalysisApplyConfiguration {
	b.Result = &value
	return b
}

// WithAnalyzedAt sets the AnalyzedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AnalyzedAt field is set to the value of the last call.
func (b *SegmentAnalysisApplyConfiguration) WithAnalyzedAt(value v1.Time) *SegmentAnalysisApplyConfiguration {
	b.AnalyzedAt = &value
	return b
}

// WithForProbeHash sets the ForProbeHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForProbeHash field is set to the value of the last call.
func (b *SegmentAnalysisApplyConfiguration) WithForProbeHash(value string) *SegmentAnalysisApplyConfiguration {
	b.ForProbeHash = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *SegmentAnalysisApplyConfiguration) WithVersion(value int32) *SegmentAnalysisApplyConfiguration {
	b.Version = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *SegmentAnalysisApplyConfiguration) WithMessage(value string) *SegmentAnalysisApplyConfiguration {
	b.Message = &value
	return b
}
