/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SeriesLinkApplyConfiguration represents a declarative configuration of the SeriesLink type for use
// with apply.
//
// SeriesLink places a book or audiobook inside a reading order.
type SeriesLinkApplyConfiguration struct {
	// Series is the name of the series.
	Series *string `json:"series,omitempty"`
	// Position is the position within the series, e.g. "3" or "2.5".
	Position *string `json:"position,omitempty"`
	// Primary is true for the series a work is chiefly part of.
	Primary *bool `json:"primary,omitempty"`
}

// SeriesLinkApplyConfiguration constructs a declarative configuration of the SeriesLink type for use with
// apply.
func SeriesLink() *SeriesLinkApplyConfiguration {
	return &SeriesLinkApplyConfiguration{}
}

// WithSeries sets the Series field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Series field is set to the value of the last call.
func (b *SeriesLinkApplyConfiguration) WithSeries(value string) *SeriesLinkApplyConfiguration {
	b.Series = &value
	return b
}

// WithPosition sets the Position field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Position field is set to the value of the last call.
func (b *SeriesLinkApplyConfiguration) WithPosition(value string) *SeriesLinkApplyConfiguration {
	b.Position = &value
	return b
}

// WithPrimary sets the Primary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Primary field is set to the value of the last call.
func (b *SeriesLinkApplyConfiguration) WithPrimary(value bool) *SeriesLinkApplyConfiguration {
	b.Primary = &value
	return b
}
