/*
Copyright 2026 The Clustarr Authors.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TrackApplyConfiguration represents a declarative configuration of the Track type for use
// with apply.
//
// Track is one recording on the selected release of an album.
type TrackApplyConfiguration struct {
	// RecordingID is the MusicBrainz recording MBID.
	RecordingID *string `json:"recordingID,omitempty"`
	// Medium is the 1-based medium the track sits on.
	Medium *int32 `json:"medium,omitempty"`
	// Number is the track number within the medium.
	Number *int32 `json:"number,omitempty"`
	// AbsoluteNumber is the track number across the whole release.
	AbsoluteNumber *int32 `json:"absoluteNumber,omitempty"`
	// Title is the track title.
	Title *string `json:"title,omitempty"`
	// DurationMs is the track duration in milliseconds.
	DurationMs *int32 `json:"durationMs,omitempty"`
	// Explicit marks a track with an explicit-content advisory.
	Explicit *bool `json:"explicit,omitempty"`
	// FileRef is the name of the MediaFile holding this track.
	FileRef *string `json:"fileRef,omitempty"`
}

// TrackApplyConfiguration constructs a declarative configuration of the Track type for use with
// apply.
func Track() *TrackApplyConfiguration {
	return &TrackApplyConfiguration{}
}

// WithRecordingID sets the RecordingID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordingID field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithRecordingID(value string) *TrackApplyConfiguration {
	b.RecordingID = &value
	return b
}

// WithMedium sets the Medium field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Medium field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithMedium(value int32) *TrackApplyConfiguration {
	b.Medium = &value
	return b
}

// WithNumber sets the Number field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Number field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithNumber(value int32) *TrackApplyConfiguration {
	b.Number = &value
	return b
}

// WithAbsoluteNumber sets the AbsoluteNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AbsoluteNumber field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithAbsoluteNumber(value int32) *TrackApplyConfiguration {
	b.AbsoluteNumber = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithTitle(value string) *TrackApplyConfiguration {
	b.Title = &value
	return b
}

// WithDurationMs sets the DurationMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DurationMs field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithDurationMs(value int32) *TrackApplyConfiguration {
	b.DurationMs = &value
	return b
}

// WithExplicit sets the Explicit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Explicit field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithExplicit(value bool) *TrackApplyConfiguration {
	b.Explicit = &value
	return b
}

// WithFileRef sets the FileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FileRef field is set to the value of the last call.
func (b *TrackApplyConfiguration) WithFileRef(value string) *TrackApplyConfiguration {
	b.FileRef = &value
	return b
}
